/**
 * lucide-react 图标中文映射生成器
 *
 * 用法:`node scripts/gen-icon-zh.cjs`(在 react/ 目录下)
 * 产出:`src/components/icon-zh.ts` —— 把 1800+ 个 lucide 图标名映射为中文关键词串
 *
 * 工作方式:
 *  1. 通过 `Object.keys(lucide-react)` 拿到所有以 Icon 结尾的导出名(排除 Icon / LucideIcon)
 *  2. 把 PascalCase 拆成 token(`BookOpenIcon` → ["Book", "Open"])
 *  3. 每个 token 查 TOKENS 字典翻译,拼成 "书 打开" 这样的字符串
 *  4. 对于无法良好直译的复合词,在 OVERRIDES 里直接给出整词翻译
 *
 * 字典覆盖率不必 100%,缺失的 token 会保留英文,所以搜索英文仍然有效。
 * 如果觉得某个图标译得别扭,直接编辑 OVERRIDES 重跑即可。
 */
const fs = require('fs');
const path = require('path');
const lucide = require('lucide-react');

/* ────────── 1. 拿全量图标名 ────────── */

const ICON_NAMES = Object.keys(lucide)
  .filter(
    (k) =>
      /^[A-Z]/.test(k) &&
      k.endsWith('Icon') &&
      k !== 'Icon' &&
      k !== 'LucideIcon',
  )
  .sort();

/* ────────── 2. 整词覆盖(OVERRIDES) ────────── */
// 一些常见的、按 token 直译会很奇怪的图标,在这里直接给定中文
const OVERRIDES = {
  AArrowDownIcon: '字号减小 字体缩小',
  AArrowUpIcon: '字号增大 字体放大',
  ALargeSmallIcon: '字号 字体大小',
  AtSignIcon: '@ 邮箱符号',
  AtSignsIcon: '@ 邮箱符号',
  BluetoothIcon: '蓝牙',
  BluetoothConnectedIcon: '蓝牙 已连接',
  BluetoothOffIcon: '蓝牙 关闭',
  BluetoothSearchingIcon: '蓝牙 搜索中',
  CommandIcon: '命令键',
  CornerDownLeftIcon: '回车 左下转角',
  CornerDownRightIcon: '右下转角',
  CornerLeftDownIcon: '左下转角',
  CornerLeftUpIcon: '左上转角',
  CornerRightDownIcon: '右下转角',
  CornerRightUpIcon: '右上转角',
  CornerUpLeftIcon: '左上转角',
  CornerUpRightIcon: '右上转角',
  EllipsisIcon: '更多 三点',
  EllipsisVerticalIcon: '更多 竖三点',
  EuroIcon: '欧元',
  GroupIcon: '组',
  HamIcon: '火腿',
  HashIcon: '井号 #',
  IceCreamConeIcon: '冰淇淋蛋筒',
  IceCream2Icon: '冰淇淋',
  InfoIcon: '信息 i',
  KanbanIcon: '看板',
  LucideIcon: '图标',
  MoonIcon: '月亮 暗色模式',
  MoonStarIcon: '月亮 星 暗色模式',
  PauseIcon: '暂停',
  PercentIcon: '百分号',
  PoundSterlingIcon: '英镑',
  RussianRubleIcon: '卢布',
  SaveIcon: '保存',
  SaveAllIcon: '保存全部',
  SearchIcon: '搜索 放大镜',
  SettingsIcon: '设置 齿轮',
  Settings2Icon: '设置 齿轮',
  SunIcon: '太阳 亮色模式',
  SunMoonIcon: '日月 切换主题',
  SunMediumIcon: '太阳 中',
  SunDimIcon: '太阳 暗',
  SunSnowIcon: '太阳雪',
  XIcon: 'X 关闭',
  ZapIcon: '闪电 速度',
  YenIcon: '日元',
  JapaneseYenIcon: '日元',
  MailIcon: '邮件 信封',
  MailsIcon: '多封邮件',
  TrashIcon: '删除 垃圾桶',
  Trash2Icon: '删除 垃圾桶',
  HomeIcon: '主页 房子',
  HouseIcon: '房子',
  Building2Icon: '楼房',
  Heart2Icon: '心',
  PencilLineIcon: '铅笔横线 编辑',
  PenLineIcon: '钢笔横线 编辑',
  TerminalIcon: '终端 控制台',
  TerminalSquareIcon: '终端 方块',
  CodeIcon: '代码 尖括号',
  Code2Icon: '代码',
  CrossIcon: '十字',
  CircleIcon: '圆',
  SquareIcon: '方块',
  RectangleHorizontalIcon: '横矩形',
  RectangleVerticalIcon: '竖矩形',
  TriangleIcon: '三角形',
  HexagonIcon: '六边形',
  OctagonIcon: '八边形',
  PentagonIcon: '五边形',
  CheckIcon: '勾选 对号',
  CheckCheckIcon: '双勾选 已读',
  CheckSquareIcon: '方块勾选',
  CheckCircleIcon: '圆形勾选',
  PlusIcon: '加号',
  MinusIcon: '减号',
  EqualIcon: '等号',
  EqualNotIcon: '不等号',
  DivideIcon: '除号',
  AsteriskIcon: '星号 *',
  CircleAlertIcon: '警告 圆',
  TriangleAlertIcon: '警告 三角',
  OctagonAlertIcon: '警告 八角',
  ShieldAlertIcon: '盾牌 警告',
  ShieldCheckIcon: '盾牌 验证',
  ShieldXIcon: '盾牌 关闭',
  ShieldOffIcon: '盾牌 关闭',
  EyeIcon: '眼睛 查看',
  EyeOffIcon: '隐藏 眼睛关闭',
  EyeClosedIcon: '眼睛闭上 隐藏',
  KeyIcon: '钥匙',
  KeyRoundIcon: '圆头钥匙',
  KeySquareIcon: '方头钥匙',
  LockIcon: '锁',
  LockOpenIcon: '开锁',
  LockKeyholeIcon: '锁孔',
  LockKeyholeOpenIcon: '开锁',
  UnlockIcon: '解锁',
  UnlockKeyholeIcon: '解锁',
  LogInIcon: '登录',
  LogOutIcon: '登出',
  RefreshCcwIcon: '逆时针刷新',
  RefreshCwIcon: '顺时针刷新',
  RefreshCcwDotIcon: '刷新',
  RefreshCwOffIcon: '停止刷新',
  RotateCcwIcon: '逆时针旋转',
  RotateCwIcon: '顺时针旋转',
  Rotate3dIcon: '3D旋转',
  ChevronUpIcon: '向上箭头',
  ChevronDownIcon: '向下箭头',
  ChevronLeftIcon: '向左箭头',
  ChevronRightIcon: '向右箭头',
  ChevronsUpIcon: '双向上箭头',
  ChevronsDownIcon: '双向下箭头',
  ChevronsLeftIcon: '双向左箭头',
  ChevronsRightIcon: '双向右箭头',
  ChevronsLeftRightIcon: '左右双箭头 收起',
  ChevronsRightLeftIcon: '右左双箭头 展开',
  ChevronsUpDownIcon: '上下双箭头',
  ChevronsDownUpIcon: '上下双箭头',
  ChevronFirstIcon: '首页 跳到开始',
  ChevronLastIcon: '末页 跳到结尾',
  ArrowUpIcon: '向上箭头',
  ArrowDownIcon: '向下箭头',
  ArrowLeftIcon: '向左箭头',
  ArrowRightIcon: '向右箭头',
  ArrowUpDownIcon: '上下箭头',
  ArrowDownUpIcon: '上下箭头',
  ArrowLeftRightIcon: '左右箭头',
  ArrowRightLeftIcon: '左右箭头 切换',
  CircleArrowUpIcon: '上箭头 圆',
  CircleArrowDownIcon: '下箭头 圆',
  CircleArrowLeftIcon: '左箭头 圆',
  CircleArrowRightIcon: '右箭头 圆',
  ArrowUpCircleIcon: '上箭头 圆',
  ArrowDownCircleIcon: '下箭头 圆',
  ArrowLeftCircleIcon: '左箭头 圆',
  ArrowRightCircleIcon: '右箭头 圆',
  ArrowUpSquareIcon: '上箭头 方',
  ArrowDownSquareIcon: '下箭头 方',
  ArrowLeftSquareIcon: '左箭头 方',
  ArrowRightSquareIcon: '右箭头 方',
  MoveUpIcon: '向上移动',
  MoveDownIcon: '向下移动',
  MoveLeftIcon: '向左移动',
  MoveRightIcon: '向右移动',
  MoveHorizontalIcon: '水平移动',
  MoveVerticalIcon: '垂直移动',
  MoveDiagonalIcon: '对角线移动',
  MoveDiagonal2Icon: '对角线移动',
  HelpCircleIcon: '帮助 问号',
  CircleHelpIcon: '帮助 问号',
  CircleEllipsisIcon: '更多 圆',
  CircleSlashIcon: '禁止 圆',
  CircleSlash2Icon: '禁止 圆',
  CirclePlusIcon: '加号 圆',
  CircleMinusIcon: '减号 圆',
  CircleXIcon: '关闭 圆',
  CircleCheckIcon: '勾选 圆',
  CircleCheckBigIcon: '大勾选 圆',
  CircleUserIcon: '用户 圆',
  CircleUserRoundIcon: '用户头像 圆',
  CircleDollarSignIcon: '美元 圆',
  CircleEuroIcon: '欧元 圆',
  CirclePoundSterlingIcon: '英镑 圆',
  SquarePlusIcon: '加号 方',
  SquareMinusIcon: '减号 方',
  SquareXIcon: '关闭 方',
  SquareCheckIcon: '勾选 方',
  SquareCheckBigIcon: '大勾选 方',
  SquareUserIcon: '用户 方',
  SquareUserRoundIcon: '用户头像 方',
  SquareSlashIcon: '禁止 方',
  SquarePenIcon: '编辑 方',
  Volume1Icon: '音量 小',
  Volume2Icon: '音量 大',
  VolumeIcon: '音量',
  VolumeXIcon: '静音',
  VolumeOffIcon: '静音',
  Wifi0Icon: 'WiFi 零',
  WifiZeroIcon: 'WiFi 零',
  Wifi1Icon: 'WiFi 弱',
  WifiLowIcon: 'WiFi 弱',
  Wifi2Icon: 'WiFi 中',
  WifiMediumIcon: 'WiFi 中',
  Wifi3Icon: 'WiFi 强',
  WifiHighIcon: 'WiFi 强',
  WifiOffIcon: 'WiFi 关闭',
  Signal0Icon: '信号 零',
  Signal1Icon: '信号 弱',
  Signal2Icon: '信号 中',
  Signal3Icon: '信号 强',
  Signal4Icon: '信号 满',
  BatteryFullIcon: '电池 满',
  BatteryLowIcon: '电池 低',
  BatteryMediumIcon: '电池 中',
  BatteryChargingIcon: '电池 充电中',
  BatteryWarningIcon: '电池 警告',
  BatteryIcon: '电池',
  ZapOffIcon: '闪电 关闭',
  Loader2Icon: '加载中 旋转',
  LoaderIcon: '加载中',
  LoaderCircleIcon: '加载中 圆',
  LoaderPinwheelIcon: '加载中 风车',
};

/* ────────── 3. Token 字典(可组合) ────────── */
// 写法:英文 token → 中文(允许带空格,作为多关键词)
// PascalCase 拆分时,每个 token 来这里查一次,组合时空格分隔
const TOKENS = {
  /* 字母 / 数字会原样保留,这里只列字母例外名 */
  A: 'A', B: 'B', C: 'C', D: 'D',

  /* —— 抽象概念 / 状态 —— */
  Activity: '活动 心电图',
  Add: '添加',
  Align: '对齐',
  Alert: '警告',
  Alarm: '闹钟',
  All: '全部',
  Always: '始终',
  Around: '周围',
  Audio: '音频',
  Auto: '自动',
  Axes: '坐标轴',
  Axis: '轴',
  Back: '后退',
  Between: '之间',
  Big: '大',
  Bold: '加粗',
  Bottom: '底部',
  Cancel: '取消',
  Case: '大小写',
  Center: '居中',
  Check: '勾选',
  Circle: '圆',
  Close: '关闭',
  Closed: '已关闭',
  Cog: '齿轮',
  Comment: '评论',
  Connected: '已连接',
  Copy: '复制',
  Dashed: '虚线',
  Dash: '虚线',
  Decrease: '减少',
  Default: '默认',
  Delete: '删除',
  Disabled: '禁用',
  Distribute: '分布',
  Done: '完成',
  Down: '下',
  Drag: '拖动',
  Drop: '放下',
  Edit: '编辑',
  Ellipsis: '省略',
  Empty: '空',
  End: '末',
  Enter: '回车',
  Equal: '等号',
  Error: '错误',
  Exit: '退出',
  Expand: '展开',
  External: '外部',
  Fading: '淡入淡出',
  First: '首',
  Fold: '折叠',
  Forward: '前进',
  From: '从',
  Front: '前',
  Full: '满',
  Half: '半',
  Hidden: '隐藏',
  Hide: '隐藏',
  High: '高',
  Horizonal: '水平',
  Horizontal: '水平',
  Idle: '空闲',
  In: '进入',
  Inactive: '未激活',
  Increase: '增加',
  Increasing: '增长',
  Input: '输入',
  Inside: '内',
  Italic: '斜体',
  Justify: '两端对齐',
  Large: '大',
  Last: '末',
  Left: '左',
  Line: '线',
  Loading: '加载中',
  Lock: '锁定',
  Low: '低',
  Mark: '标记',
  Maximize: '最大化',
  Medium: '中',
  Menu: '菜单',
  Middle: '中',
  Minimal: '极简',
  Minimize: '最小化',
  Minus: '减',
  More: '更多',
  Mute: '静音',
  Narrow: '窄',
  New: '新建',
  No: '无',
  Normal: '正常',
  Not: '不',
  Off: '关闭',
  On: '开启',
  Once: '一次',
  Online: '在线',
  Open: '打开',
  Out: '出',
  Outside: '外',
  Pause: '暂停',
  Pending: '等待',
  Pin: '置顶',
  Plus: '加',
  Power: '电源',
  Public: '公开',
  Pull: '拉',
  Push: '推',
  Reply: '回复',
  Remove: '移除',
  Reset: '重置',
  Restore: '恢复',
  Right: '右',
  Round: '圆',
  Rounded: '圆角',
  Save: '保存',
  Search: '搜索',
  Send: '发送',
  Settings: '设置',
  Share: '分享',
  Show: '显示',
  Slash: '斜杠',
  Slow: '慢',
  Small: '小',
  Sort: '排序',
  Square: '方块',
  Start: '开始',
  Stop: '停止',
  Sub: '子',
  Sync: '同步',
  Top: '顶',
  Unfold: '展开',
  Unlock: '解锁',
  Unread: '未读',
  Up: '上',
  Update: '更新',
  Upload: '上传',
  Vertical: '垂直',
  View: '查看',
  Warning: '警告',
  Wide: '宽',
  X: 'X',
  Zero: '零',
  Zoom: '缩放',

  /* —— 名词 / 物体 —— */
  Accessibility: '无障碍',
  Air: '空气',
  Airplay: 'Airplay 无线投屏',
  Album: '相册',
  Ambulance: '救护车',
  Ampersand: '&',
  Amphora: '陶罐',
  Anchor: '锚',
  Angry: '愤怒',
  Annoyed: '厌烦',
  Antenna: '天线',
  Aperture: '光圈',
  Anvil: '铁砧',
  App: '应用',
  Apple: '苹果',
  Archive: '归档',
  Area: '区域',
  Armchair: '扶手椅',
  Arrow: '箭头',
  Award: '奖章',
  Axe: '斧头',
  Backpack: '背包',
  Badge: '徽章',
  Ban: '禁止',
  Banana: '香蕉',
  Bandage: '绷带',
  Banknote: '钞票',
  Bar: '条',
  Barcode: '条码',
  Baseline: '基线',
  Bath: '浴缸',
  Battery: '电池',
  Beaker: '量杯',
  Bed: '床',
  Beef: '牛肉',
  Beer: '啤酒',
  Bell: '铃铛 通知',
  Binary: '二进制',
  Biohazard: '生物危害',
  Bird: '鸟',
  Bitcoin: '比特币',
  Blend: '混合',
  Blinds: '百叶窗',
  Blocks: '积木',
  Bluetooth: '蓝牙',
  Bolt: '螺栓',
  Bomb: '炸弹',
  Bone: '骨头',
  Book: '书',
  Booking: '预订',
  Bookmark: '书签',
  Bot: '机器人',
  Box: '盒子',
  Boxes: '多个盒子',
  Braces: '花括号',
  Brackets: '方括号',
  Brain: '大脑',
  Briefcase: '公文包',
  Brick: '砖',
  Brush: '画笔',
  Building: '建筑',
  Bug: '虫',
  Bus: '巴士',
  Cable: '线缆',
  Cake: '蛋糕',
  Calculator: '计算器',
  Calendar: '日历',
  Camera: '相机',
  Camping: '露营',
  Candy: '糖果',
  Cannabis: '大麻',
  Captions: '字幕',
  Car: '汽车',
  Card: '卡片',
  Carrot: '胡萝卜',
  Cast: '投屏',
  Castle: '城堡',
  Cat: '猫',
  Cctv: '监控',
  Chart: '图表',
  Cherry: '樱桃',
  Chess: '国际象棋',
  Chevron: '箭头',
  Chrome: 'Chrome',
  Church: '教堂',
  Cigarette: '香烟',
  Citrus: '柑橘',
  Clapper: '场记板',
  Clipboard: '剪贴板',
  Clock: '时钟',
  Cloud: '云',
  Cloudy: '多云',
  Clover: '三叶草',
  Club: '梅花',
  Code: '代码',
  Coffee: '咖啡',
  Coin: '硬币',
  Coins: '硬币',
  Column: '列',
  Columns: '列',
  Combine: '合并',
  Compass: '指南针',
  Component: '组件',
  Computer: '电脑',
  Concierge: '前台',
  Cone: '圆锥',
  Confused: '困惑',
  Construction: '施工',
  Contact: '联系人',
  Container: '容器',
  Contrast: '对比度',
  Cookie: '饼干',
  Corner: '转角',
  Cpu: 'CPU',
  Crane: '吊车',
  Credit: '信用',
  Croissant: '牛角包',
  Crop: '裁剪',
  Crosshair: '十字准线',
  Crown: '皇冠',
  Cuboid: '立方体',
  Cup: '杯子',
  Currency: '货币',
  Cylinder: '圆柱',
  Dam: '水坝',
  Database: '数据库',
  Decimal: '小数',
  Deer: '鹿',
  Delivery: '配送',
  Dessert: '甜点',
  Diameter: '直径',
  Diamond: '钻石',
  Dice: '骰子',
  Diff: '差异',
  Disc: '光盘',
  Divide: '除',
  Dna: 'DNA',
  Dock: '船坞',
  Document: '文档',
  Dog: '狗',
  Dollar: '美元',
  Donut: '甜甜圈',
  Door: '门',
  Dot: '点',
  Download: '下载',
  Drafting: '绘图',
  Drill: '钻',
  Droplet: '水滴',
  Droplets: '水滴',
  Drum: '鼓',
  Drumstick: '鸡腿',
  Dumbbell: '哑铃',
  Ear: '耳朵',
  Earth: '地球',
  Egg: '鸡蛋',
  Eraser: '橡皮',
  Eye: '眼睛',
  Facebook: 'Facebook',
  Factory: '工厂',
  Fan: '风扇',
  Feather: '羽毛',
  Fence: '栅栏',
  Ferris: '摩天轮',
  Figma: 'Figma',
  File: '文件',
  Files: '多文件',
  Film: '胶片',
  Filter: '筛选',
  Fingerprint: '指纹',
  Fire: '火',
  Fish: '鱼',
  Flag: '旗帜',
  Flame: '火焰',
  Flashlight: '手电筒',
  Flask: '烧瓶',
  Flip: '翻转',
  Flower: '花',
  Focus: '聚焦',
  Folder: '文件夹',
  Folders: '多文件夹',
  Footprints: '脚印',
  Fork: '叉',
  Forklift: '叉车',
  Franc: '法郎',
  Frame: '边框',
  Framer: 'Framer',
  Frown: '皱眉',
  Fuel: '燃料',
  Funnel: '漏斗',
  Gantt: '甘特图',
  Gallery: '画廊',
  Gamepad: '游戏手柄',
  Gauge: '仪表',
  Gavel: '法槌',
  Gem: '宝石',
  Ghost: '幽灵',
  Gift: '礼物',
  Git: 'Git',
  Github: 'Github',
  Gitlab: 'Gitlab',
  Glass: '玻璃',
  Glasses: '眼镜',
  Globe: '地球',
  Goal: '目标',
  Grab: '抓取',
  Graduation: '毕业',
  Grape: '葡萄',
  Grid: '网格',
  Grip: '把手',
  Guitar: '吉他',
  Hammer: '锤',
  Hand: '手',
  Handshake: '握手',
  Hard: '硬',
  Hash: '井号',
  Hat: '帽子',
  Haze: '薄雾',
  Hdmi: 'HDMI',
  Heading: '标题',
  Headphone: '耳机',
  Headphones: '耳机',
  Headset: '头戴耳机',
  Heart: '心',
  Heater: '加热器',
  Helmet: '头盔',
  Help: '帮助',
  Hexagon: '六边形',
  Highlighter: '荧光笔',
  History: '历史',
  Home: '主页',
  Hop: '啤酒花',
  Hospital: '医院',
  Hotel: '酒店',
  Hourglass: '沙漏',
  House: '房子',
  Ice: '冰',
  Image: '图片',
  Images: '多图片',
  Import: '导入',
  Inbox: '收件箱',
  Indent: '缩进',
  Indian: '印度',
  Infinity: '无限',
  Info: '信息',
  Inspect: '检查',
  Instagram: 'Instagram',
  Japanese: '日本',
  Joystick: '摇杆',
  Kanban: '看板',
  Key: '钥匙',
  Keyboard: '键盘',
  Keyhole: '锁孔',
  Knife: '刀',
  Lamp: '灯',
  Landmark: '地标',
  Landplot: '土地',
  Language: '语言',
  Languages: '语言',
  Laptop: '笔记本',
  Lasso: '套索',
  Laugh: '大笑',
  Layers: '图层',
  Layout: '布局',
  Leaf: '叶',
  Leafy: '多叶',
  Library: '图书馆',
  Lightbulb: '灯泡',
  Lightning: '闪电',
  Link: '链接',
  Linkedin: 'LinkedIn',
  Lira: '里拉',
  List: '列表',
  Locate: '定位',
  Location: '位置',
  Log: '日志',
  Logs: '日志',
  Mac: 'Mac',
  Mail: '邮件',
  Map: '地图',
  Mars: '火星',
  Martini: '马提尼',
  Medal: '奖牌',
  Megaphone: '喇叭',
  Meh: '平淡',
  Merge: '合并',
  Message: '消息',
  Messages: '消息',
  Meter: '米',
  Mic: '麦克风',
  Microscope: '显微镜',
  Microwave: '微波炉',
  Milestone: '里程碑',
  Milk: '牛奶',
  Mist: '雾',
  Monitor: '显示器',
  Moon: '月亮',
  Mountain: '山',
  Mouse: '鼠标',
  Move: '移动',
  Music: '音乐',
  Navigation: '导航',
  Network: '网络',
  Newspaper: '报纸',
  Nfc: 'NFC',
  Notebook: '笔记本',
  Notepad: '记事本',
  Nut: '螺母',
  Octagon: '八边形',
  Omega: '欧米茄',
  Option: '选项',
  Orbit: '轨道',
  Origami: '折纸',
  Package: '包裹',
  Page: '页',
  Panels: '面板',
  Paint: '漆',
  Paintbrush: '画刷',
  Palette: '调色板',
  Palmtree: '棕榈树',
  Panda: '熊猫',
  Panel: '面板',
  Paperclip: '回形针',
  Parentheses: '括号',
  Parking: '停车',
  Party: '派对',
  Paw: '爪',
  Pc: '机箱',
  Pen: '钢笔',
  Pencil: '铅笔',
  Pentagon: '五边形',
  Percent: '百分号',
  Person: '人',
  Phone: '电话',
  Pi: 'π',
  Piano: '钢琴',
  Pickaxe: '镐',
  Picture: '图片',
  Pie: '饼图',
  Piggy: '储蓄罐',
  Pilcrow: '段落符',
  Pill: '药丸',
  Pin: '大头针',
  Pipette: '移液器',
  Pizza: '披萨',
  Plane: '飞机',
  Plant: '植物',
  Play: '播放',
  Plug: '插头',
  Pocket: '口袋',
  Podcast: '播客',
  Pointer: '指针',
  Police: '警察',
  Popcorn: '爆米花',
  Popsicle: '雪糕',
  Pound: '英镑',
  Presentation: '演示',
  Printer: '打印机',
  Projector: '投影仪',
  Proportions: '比例',
  Puzzle: '拼图',
  Pyramid: '金字塔',
  Qr: '二维码',
  Question: '问号',
  Quote: '引用',
  Rabbit: '兔子',
  Radar: '雷达',
  Radiation: '辐射',
  Radical: '根号',
  Radio: '收音机',
  Radius: '半径',
  Rail: '铁路',
  Rain: '雨',
  Rainbow: '彩虹',
  Rat: '老鼠',
  Receipt: '收据',
  Rectangle: '矩形',
  Recycle: '回收',
  Redo: '重做',
  Refresh: '刷新',
  Refrigerator: '冰箱',
  Regex: '正则',
  Repeat: '重复',
  Replace: '替换',
  Request: '请求',
  Restore: '恢复',
  Rewind: '倒带',
  Ribbon: '丝带',
  Rocket: '火箭',
  Rocking: '摇',
  Roller: '滚轴',
  Rotate: '旋转',
  Route: '路线',
  Router: '路由器',
  Rows: '行',
  Rss: 'RSS',
  Ruler: '尺',
  Rupee: '卢比',
  Sad: '悲伤',
  Sailboat: '帆船',
  Salad: '沙拉',
  Sandwich: '三明治',
  Satellite: '卫星',
  Scale: '秤',
  Scaling: '缩放',
  Scan: '扫描',
  School: '学校',
  Scissors: '剪刀',
  Screen: '屏幕',
  Scroll: '卷轴',
  Sd: 'SD',
  Section: '段',
  Select: '选择',
  Separator: '分隔符',
  Server: '服务器',
  Sidebar: '侧边栏',
  Shapes: '形状',
  Sheet: '表单',
  Shell: '贝壳',
  Shield: '盾牌',
  Ship: '船',
  Shirt: '衬衣',
  Shopping: '购物',
  Shovel: '铲',
  Shower: '淋浴',
  Shrub: '灌木',
  Shrink: '收缩',
  Shuffle: '随机',
  Sigma: 'Σ',
  Signal: '信号',
  Signature: '签名',
  Signpost: '路牌',
  Siren: '警报',
  Skip: '跳过',
  Skull: '骷髅',
  Slack: 'Slack',
  Slice: '切片',
  Slider: '滑块',
  Sliders: '滑块',
  Smartphone: '智能手机',
  Smile: '笑脸',
  Smoke: '烟',
  Snail: '蜗牛',
  Snowflake: '雪花',
  Snowman: '雪人',
  Sofa: '沙发',
  Soup: '汤',
  Space: '空格',
  Spade: '黑桃',
  Sparkle: '闪光',
  Sparkles: '闪光',
  Speaker: '扬声器',
  Speech: '言语',
  Spline: '曲线',
  Split: '分割',
  Spray: '喷雾',
  Sprout: '嫩芽',
  Squares: '方块',
  Squircle: '圆角方块',
  Squirrel: '松鼠',
  Stamp: '印章',
  Star: '星',
  Stars: '星群',
  Step: '步',
  Sterling: '英镑',
  Stethoscope: '听诊器',
  Sticker: '贴纸',
  Sticky: '便利',
  Store: '商店',
  Stretch: '拉伸',
  Strikethrough: '删除线',
  Subscript: '下标',
  Subtitles: '字幕',
  Sun: '太阳',
  Sunrise: '日出',
  Sunset: '日落',
  Superscript: '上标',
  Surface: '表面',
  Swatch: '色板',
  Swiss: '瑞士',
  Sword: '剑',
  Swords: '剑',
  Syringe: '注射器',
  Table: '表格',
  Tablet: '平板',
  Tablets: '药片',
  Tag: '标签',
  Tags: '标签',
  Tally: '计数',
  Tangent: '切线',
  Target: '靶心',
  Telescope: '望远镜',
  Tent: '帐篷',
  Test: '测试',
  Text: '文本',
  Theater: '剧院',
  Thermometer: '温度计',
  Thumbs: '点赞',
  Ticket: '票',
  Tilt: '倾斜',
  Timer: '计时器',
  To: '到',
  Toggle: '开关',
  Toilet: '马桶',
  Tornado: '龙卷风',
  Torus: '圆环',
  Tower: '塔',
  Toy: '玩具',
  Tractor: '拖拉机',
  Traffic: '交通',
  Train: '火车',
  Tram: '电车',
  Tree: '树',
  Trees: '树林',
  Trello: 'Trello',
  Trending: '趋势',
  Triangle: '三角形',
  Trophy: '奖杯',
  Truck: '卡车',
  Tube: '管',
  Turkish: '土耳其',
  Turtle: '乌龟',
  Tv: '电视',
  Twitch: 'Twitch',
  Twitter: '推特',
  Type: '文字',
  Umbrella: '雨伞',
  Underline: '下划线',
  Undo: '撤销',
  Unfold: '展开',
  Unlink: '取消链接',
  Unplug: '拔插头',
  Usb: 'USB',
  User: '用户',
  Users: '用户群',
  Utensils: '餐具',
  Utility: '电线',
  Vault: '保险柜',
  Vegan: '素食',
  Venetian: '威尼斯',
  Vent: '通风口',
  Verified: '已验证',
  Vibrate: '震动',
  Video: '视频',
  Videos: '视频',
  Vines: '藤蔓',
  Voicemail: '语音邮件',
  Volcano: '火山',
  Volleyball: '排球',
  Volume: '音量',
  Vote: '投票',
  Wall: '墙',
  Wallet: '钱包',
  Wallpaper: '壁纸',
  Wand: '魔棒',
  Warehouse: '仓库',
  Washing: '洗衣',
  Watch: '手表',
  Waves: '波浪',
  Waypoints: '路径点',
  Webcam: '摄像头',
  Webhook: 'Webhook',
  Weight: '重量',
  Wheat: '麦穗',
  Wifi: 'WiFi',
  Wind: '风',
  Window: '窗口',
  Wine: '红酒',
  Workflow: '工作流',
  Wrap: '换行',
  Wrench: '扳手',
  Yen: '日元',
  Youtube: 'YouTube',
  Zap: '闪电',
  Z: 'Z',

  /* —— 状态修饰 / 衍生词 —— */
  Crack: '裂',
  Pulse: '跳动',
  Pinwheel: '风车',
  Cube: '立方体',
  Russian: '俄罗斯',
  Ruble: '卢布',
  Br: 'Br',
  AZ: 'A-Z',
  Az: 'a-z',
  ZA: 'Z-A',
  Za: 'z-a',
  Cw: '顺时针',
  Ccw: '逆时针',
  Platter: '托盘',

  /* —— 最后一轮补遗 —— */
  Branch: '分支',
  Commit: '提交',
  Drive: '驱动',
  Decreasing: '递减',
  Chevrons: '双箭头',
  Form: '表单',
  Function: '函数',
  Helping: '帮助',
  Id: 'ID',
  Iteration: '迭代',
  Json: 'JSON',
  Output: '输出',
  Port: '端口',
  Scatter: '散布',
  Sign: '符号',
  Snow: '雪',
  Spell: '拼写',
  Stack: '栈',
  Stacked: '堆叠',
  Symbol: '符号',
  Symlink: '软链',
  Template: '模板',
  Terminal: '终端',
  Tickets: '票',
  Tool: '工具',
  Touchpad: '触摸板',
  Venus: '金星',
  Webhook: 'Webhook',
  Wheel: '轮',
  Pull: '拉取',
  Push: '推送',
  Euro: '欧元',
  Electric: '电',
  Decimals: '小数',
  Cursor: '光标',
  Crossed: '交叉',
  Create: '创建',
  Cream: '奶油',
  Conical: '圆锥',
  Compare: '对比',
  Circuit: '电路',
  Cent: '分',
  Cells: '单元格',
  Candlestick: 'K线',
  Cable: '线缆',
  Brackets: '方括号',
  Braces: '花括号',
  Bookmark: '书签',
  Bone: '骨头',
  Bomb: '炸弹',
  Blocks: '积木',
  Blocked: '已禁止',
  Bird: '鸟',
  Binary: '二进制',
  Beaker: '量杯',
  Battery: '电池',
  Baseline: '基线',
  Banner: '横幅',
  Atom: '原子',
  Asterisk: '星号',
  Ascending: '升序',
  Descending: '降序',
  Diff: '差异',
  Decimal: '小数',
  Boom: '繁荣',
  Layout: '布局',
  Map: '地图',
  Mining: '挖矿',
  Manga: '漫画',
  Mark: '标记',
  Marker: '标记',
  Master: '主',
  Mask: '面具',
  Net: '网',
  Origin: '原点',
  Pacman: '吃豆人',
  Page2: '页',
  Phone2: '电话',
  Phones: '电话',
  Pixel: '像素',
  Plug2: '插头',
  Pose: '姿势',
  Pulse2: '跳动',
  Question2: '问号',
  Queue: '队列',
  Quotes: '引号',
  Rod: '杆',
  Rooms: '房间',
  Sea: '海',
  Seat: '座位',
  Slipper: '拖鞋',
  Solar: '太阳能',
  Spam: '垃圾邮件',
  Spinner: '加载',
  Stove: '炉灶',
  String: '字符串',
  Substring: '子串',
  Suit: '套装',
  Surf: '冲浪',
  Surfer: '冲浪',
  Tabs: '标签页',
  Target2: '靶心',
  Taxi: '出租车',
  Tic: '井字',
  Tilde: '波浪号',
  Tower2: '塔',
  Trumpet: '小号',
  Tunnel: '隧道',
  Underground: '地下',
  Unicycle: '独轮车',
  Upright: '直立',
  Usbport: 'USB端口',
  Valid: '有效',
  Vault2: '保险柜',
  Venn: '维恩',
  Vrt: 'VRT',
  Wall2: '墙',
  Wallpaper2: '壁纸',
  Wand2: '魔棒',
  Waveform: '波形',
  Whale: '鲸鱼',
  Wheelchair: '轮椅',
  Wifi2: 'WiFi',
  Windmill: '风车',
  Wood: '木',
  Word: '单词',
  Words: '单词',
  X2: 'X',
  Yam: '山药',
  Yew: '紫杉',
  Zen: '禅',
  Whole: '完整',
  Ring: '振铃',
  Days: '天数',
  Range: '范围',
  Calendars: '日历',
  Bottle: '瓶',
  Bean: '豆',
  Arrows: '箭头',
  Xml: 'XML',
  Variable: '变量',
  Vector: '向量',
  Water: '水',
  Tubes: '管',
  Upper: '上',
  Upscale: '放大',
  Vibration: '震动',
  Wallpaper2: '壁纸',
  Wifi3: 'WiFi',
  Workspace: '工作区',
  Wifi4: 'WiFi',
  Words2: '单词',
  Tooth: '牙',
  Tomb: '墓',
  Together: '一起',
  Ufo: 'UFO',
  Trumpets: '号',
  Vinyl: '黑胶',
  Vocal: '人声',
  Yang: '阳',
  Yin: '阴',
  Sailing: '航行',
  Saw: '锯',
  Scallop: '扇贝',
  Sneaker: '运动鞋',
};

/* ────────── 4. 工具函数 ────────── */

function stripIcon(name) {
  return name.replace(/Icon$/, '');
}

// PascalCase → tokens(数字单独成 token)
// 例:'BookOpen' → ['Book', 'Open']
//     'Heading1' → ['Heading', '1']
//     'AArrowDown' → ['A', 'Arrow', 'Down']
function splitTokens(name) {
  const stripped = stripIcon(name);
  // 匹配:连续大写(+后跟小写则切走)、首字母大写后跟小写、纯小写、连续数字
  const matches = stripped.match(
    /[A-Z]+(?=[A-Z][a-z])|[A-Z][a-z]+|[A-Z]+|[a-z]+|\d+/g,
  );
  return matches ?? [stripped];
}

function translate(name) {
  if (OVERRIDES[name]) return OVERRIDES[name];
  const tokens = splitTokens(name);
  const translated = tokens.map((t) => {
    // 纯数字保留
    if (/^\d+$/.test(t)) return t;
    // 1 字符大写字母保留(A、B、C 这种)
    if (/^[A-Z]$/.test(t)) return t;
    const key = t.charAt(0).toUpperCase() + t.slice(1).toLowerCase();
    return TOKENS[key] || t;
  });
  return translated.join(' ');
}

/* ────────── 5. 生成 ────────── */

const result = {};
for (const n of ICON_NAMES) {
  result[n] = translate(n);
}

const outPath = path.resolve(__dirname, '../src/components/icon-zh.ts');
const content =
  `/* eslint-disable */
// 自动生成 —— 请勿手编辑(由 scripts/gen-icon-zh.cjs 生成)
// 总计:${ICON_NAMES.length} 个图标
// 重新生成:cd react && node scripts/gen-icon-zh.cjs
//
// 值是空格分隔的中文关键词,第一个词用作 tooltip 显示主名,
// 全部参与 IconPicker 的中文搜索匹配。
export const ICON_ZH: Record<string, string> = ${JSON.stringify(result, null, 2)};
`;

fs.writeFileSync(outPath, content, 'utf8');
console.log(
  `✓ 已生成 ${outPath}\n  共 ${ICON_NAMES.length} 个图标,${Object.keys(OVERRIDES).length} 条整词覆盖,${Object.keys(TOKENS).length} 个 token`,
);
