/* eslint-disable */
// 自动生成 —— 请勿手编辑(由 scripts/gen-icon-zh.cjs 生成)
// 总计:1893 个图标
// 重新生成:cd react && node scripts/gen-icon-zh.cjs
//
// 值是空格分隔的中文关键词,第一个词用作 tooltip 显示主名,
// 全部参与 IconPicker 的中文搜索匹配。
export const ICON_ZH: Record<string, string> = {
  "AArrowDownIcon": "字号减小 字体缩小",
  "AArrowUpIcon": "字号增大 字体放大",
  "ALargeSmallIcon": "字号 字体大小",
  "AccessibilityIcon": "无障碍",
  "ActivityIcon": "活动 心电图",
  "ActivitySquareIcon": "活动 心电图 方块",
  "AirVentIcon": "空气 通风口",
  "AirplayIcon": "Airplay 无线投屏",
  "AlarmCheckIcon": "闹钟 勾选",
  "AlarmClockCheckIcon": "闹钟 时钟 勾选",
  "AlarmClockIcon": "闹钟 时钟",
  "AlarmClockMinusIcon": "闹钟 时钟 减",
  "AlarmClockOffIcon": "闹钟 时钟 关闭",
  "AlarmClockPlusIcon": "闹钟 时钟 加",
  "AlarmMinusIcon": "闹钟 减",
  "AlarmPlusIcon": "闹钟 加",
  "AlarmSmokeIcon": "闹钟 烟",
  "AlbumIcon": "相册",
  "AlertCircleIcon": "警告 圆",
  "AlertOctagonIcon": "警告 八边形",
  "AlertTriangleIcon": "警告 三角形",
  "AlignCenterHorizontalIcon": "对齐 居中 水平",
  "AlignCenterIcon": "对齐 居中",
  "AlignCenterVerticalIcon": "对齐 居中 垂直",
  "AlignEndHorizontalIcon": "对齐 末 水平",
  "AlignEndVerticalIcon": "对齐 末 垂直",
  "AlignHorizontalDistributeCenterIcon": "对齐 水平 分布 居中",
  "AlignHorizontalDistributeEndIcon": "对齐 水平 分布 末",
  "AlignHorizontalDistributeStartIcon": "对齐 水平 分布 开始",
  "AlignHorizontalJustifyCenterIcon": "对齐 水平 两端对齐 居中",
  "AlignHorizontalJustifyEndIcon": "对齐 水平 两端对齐 末",
  "AlignHorizontalJustifyStartIcon": "对齐 水平 两端对齐 开始",
  "AlignHorizontalSpaceAroundIcon": "对齐 水平 空格 周围",
  "AlignHorizontalSpaceBetweenIcon": "对齐 水平 空格 之间",
  "AlignJustifyIcon": "对齐 两端对齐",
  "AlignLeftIcon": "对齐 左",
  "AlignRightIcon": "对齐 右",
  "AlignStartHorizontalIcon": "对齐 开始 水平",
  "AlignStartVerticalIcon": "对齐 开始 垂直",
  "AlignVerticalDistributeCenterIcon": "对齐 垂直 分布 居中",
  "AlignVerticalDistributeEndIcon": "对齐 垂直 分布 末",
  "AlignVerticalDistributeStartIcon": "对齐 垂直 分布 开始",
  "AlignVerticalJustifyCenterIcon": "对齐 垂直 两端对齐 居中",
  "AlignVerticalJustifyEndIcon": "对齐 垂直 两端对齐 末",
  "AlignVerticalJustifyStartIcon": "对齐 垂直 两端对齐 开始",
  "AlignVerticalSpaceAroundIcon": "对齐 垂直 空格 周围",
  "AlignVerticalSpaceBetweenIcon": "对齐 垂直 空格 之间",
  "AmbulanceIcon": "救护车",
  "AmpersandIcon": "&",
  "AmpersandsIcon": "Ampersands",
  "AmphoraIcon": "陶罐",
  "AnchorIcon": "锚",
  "AngryIcon": "愤怒",
  "AnnoyedIcon": "厌烦",
  "AntennaIcon": "天线",
  "AnvilIcon": "铁砧",
  "ApertureIcon": "光圈",
  "AppWindowIcon": "应用 窗口",
  "AppWindowMacIcon": "应用 窗口 Mac",
  "AppleIcon": "苹果",
  "ArchiveIcon": "归档",
  "ArchiveRestoreIcon": "归档 恢复",
  "ArchiveXIcon": "归档 X",
  "AreaChartIcon": "区域 图表",
  "ArmchairIcon": "扶手椅",
  "ArrowBigDownDashIcon": "箭头 大 下 虚线",
  "ArrowBigDownIcon": "箭头 大 下",
  "ArrowBigLeftDashIcon": "箭头 大 左 虚线",
  "ArrowBigLeftIcon": "箭头 大 左",
  "ArrowBigRightDashIcon": "箭头 大 右 虚线",
  "ArrowBigRightIcon": "箭头 大 右",
  "ArrowBigUpDashIcon": "箭头 大 上 虚线",
  "ArrowBigUpIcon": "箭头 大 上",
  "ArrowDown01Icon": "箭头 下 01",
  "ArrowDown10Icon": "箭头 下 10",
  "ArrowDownAZIcon": "箭头 下 a-z",
  "ArrowDownAzIcon": "箭头 下 a-z",
  "ArrowDownCircleIcon": "下箭头 圆",
  "ArrowDownFromLineIcon": "箭头 下 从 线",
  "ArrowDownIcon": "向下箭头",
  "ArrowDownLeftFromCircleIcon": "箭头 下 左 从 圆",
  "ArrowDownLeftFromSquareIcon": "箭头 下 左 从 方块",
  "ArrowDownLeftIcon": "箭头 下 左",
  "ArrowDownLeftSquareIcon": "箭头 下 左 方块",
  "ArrowDownNarrowWideIcon": "箭头 下 窄 宽",
  "ArrowDownRightFromCircleIcon": "箭头 下 右 从 圆",
  "ArrowDownRightFromSquareIcon": "箭头 下 右 从 方块",
  "ArrowDownRightIcon": "箭头 下 右",
  "ArrowDownRightSquareIcon": "箭头 下 右 方块",
  "ArrowDownSquareIcon": "下箭头 方",
  "ArrowDownToDotIcon": "箭头 下 到 点",
  "ArrowDownToLineIcon": "箭头 下 到 线",
  "ArrowDownUpIcon": "上下箭头",
  "ArrowDownWideNarrowIcon": "箭头 下 宽 窄",
  "ArrowDownZAIcon": "箭头 下 z-a",
  "ArrowDownZaIcon": "箭头 下 z-a",
  "ArrowLeftCircleIcon": "左箭头 圆",
  "ArrowLeftFromLineIcon": "箭头 左 从 线",
  "ArrowLeftIcon": "向左箭头",
  "ArrowLeftRightIcon": "左右箭头",
  "ArrowLeftSquareIcon": "左箭头 方",
  "ArrowLeftToLineIcon": "箭头 左 到 线",
  "ArrowRightCircleIcon": "右箭头 圆",
  "ArrowRightFromLineIcon": "箭头 右 从 线",
  "ArrowRightIcon": "向右箭头",
  "ArrowRightLeftIcon": "左右箭头 切换",
  "ArrowRightSquareIcon": "右箭头 方",
  "ArrowRightToLineIcon": "箭头 右 到 线",
  "ArrowUp01Icon": "箭头 上 01",
  "ArrowUp10Icon": "箭头 上 10",
  "ArrowUpAZIcon": "箭头 上 a-z",
  "ArrowUpAzIcon": "箭头 上 a-z",
  "ArrowUpCircleIcon": "上箭头 圆",
  "ArrowUpDownIcon": "上下箭头",
  "ArrowUpFromDotIcon": "箭头 上 从 点",
  "ArrowUpFromLineIcon": "箭头 上 从 线",
  "ArrowUpIcon": "向上箭头",
  "ArrowUpLeftFromCircleIcon": "箭头 上 左 从 圆",
  "ArrowUpLeftFromSquareIcon": "箭头 上 左 从 方块",
  "ArrowUpLeftIcon": "箭头 上 左",
  "ArrowUpLeftSquareIcon": "箭头 上 左 方块",
  "ArrowUpNarrowWideIcon": "箭头 上 窄 宽",
  "ArrowUpRightFromCircleIcon": "箭头 上 右 从 圆",
  "ArrowUpRightFromSquareIcon": "箭头 上 右 从 方块",
  "ArrowUpRightIcon": "箭头 上 右",
  "ArrowUpRightSquareIcon": "箭头 上 右 方块",
  "ArrowUpSquareIcon": "上箭头 方",
  "ArrowUpToLineIcon": "箭头 上 到 线",
  "ArrowUpWideNarrowIcon": "箭头 上 宽 窄",
  "ArrowUpZAIcon": "箭头 上 z-a",
  "ArrowUpZaIcon": "箭头 上 z-a",
  "ArrowsUpFromLineIcon": "箭头 上 从 线",
  "AsteriskIcon": "星号 *",
  "AsteriskSquareIcon": "星号 方块",
  "AtSignIcon": "@ 邮箱符号",
  "AtomIcon": "原子",
  "AudioLinesIcon": "音频 Lines",
  "AudioWaveformIcon": "音频 波形",
  "AwardIcon": "奖章",
  "AxeIcon": "斧头",
  "Axis3DIcon": "轴 3 D",
  "Axis3dIcon": "轴 3 D",
  "BabyIcon": "Baby",
  "BackpackIcon": "背包",
  "BadgeAlertIcon": "徽章 警告",
  "BadgeCentIcon": "徽章 分",
  "BadgeCheckIcon": "徽章 勾选",
  "BadgeDollarSignIcon": "徽章 美元 符号",
  "BadgeEuroIcon": "徽章 欧元",
  "BadgeHelpIcon": "徽章 帮助",
  "BadgeIcon": "徽章",
  "BadgeIndianRupeeIcon": "徽章 印度 卢比",
  "BadgeInfoIcon": "徽章 信息",
  "BadgeJapaneseYenIcon": "徽章 日本 日元",
  "BadgeMinusIcon": "徽章 减",
  "BadgePercentIcon": "徽章 百分号",
  "BadgePlusIcon": "徽章 加",
  "BadgePoundSterlingIcon": "徽章 英镑 英镑",
  "BadgeQuestionMarkIcon": "徽章 问号 标记",
  "BadgeRussianRubleIcon": "徽章 俄罗斯 卢布",
  "BadgeSwissFrancIcon": "徽章 瑞士 法郎",
  "BadgeTurkishLiraIcon": "徽章 土耳其 里拉",
  "BadgeXIcon": "徽章 X",
  "BaggageClaimIcon": "Baggage Claim",
  "BanIcon": "禁止",
  "BananaIcon": "香蕉",
  "BandageIcon": "绷带",
  "BanknoteArrowDownIcon": "钞票 箭头 下",
  "BanknoteArrowUpIcon": "钞票 箭头 上",
  "BanknoteIcon": "钞票",
  "BanknoteXIcon": "钞票 X",
  "BarChart2Icon": "条 图表 2",
  "BarChart3Icon": "条 图表 3",
  "BarChart4Icon": "条 图表 4",
  "BarChartBigIcon": "条 图表 大",
  "BarChartHorizontalBigIcon": "条 图表 水平 大",
  "BarChartHorizontalIcon": "条 图表 水平",
  "BarChartIcon": "条 图表",
  "BarcodeIcon": "条码",
  "BarrelIcon": "Barrel",
  "BaselineIcon": "基线",
  "BathIcon": "浴缸",
  "BatteryChargingIcon": "电池 充电中",
  "BatteryFullIcon": "电池 满",
  "BatteryIcon": "电池",
  "BatteryLowIcon": "电池 低",
  "BatteryMediumIcon": "电池 中",
  "BatteryPlusIcon": "电池 加",
  "BatteryWarningIcon": "电池 警告",
  "BeakerIcon": "量杯",
  "BeanIcon": "豆",
  "BeanOffIcon": "豆 关闭",
  "BedDoubleIcon": "床 Double",
  "BedIcon": "床",
  "BedSingleIcon": "床 Single",
  "BeefIcon": "牛肉",
  "BeerIcon": "啤酒",
  "BeerOffIcon": "啤酒 关闭",
  "BellDotIcon": "铃铛 通知 点",
  "BellElectricIcon": "铃铛 通知 电",
  "BellIcon": "铃铛 通知",
  "BellMinusIcon": "铃铛 通知 减",
  "BellOffIcon": "铃铛 通知 关闭",
  "BellPlusIcon": "铃铛 通知 加",
  "BellRingIcon": "铃铛 通知 振铃",
  "BetweenHorizonalEndIcon": "之间 水平 末",
  "BetweenHorizonalStartIcon": "之间 水平 开始",
  "BetweenHorizontalEndIcon": "之间 水平 末",
  "BetweenHorizontalStartIcon": "之间 水平 开始",
  "BetweenVerticalEndIcon": "之间 垂直 末",
  "BetweenVerticalStartIcon": "之间 垂直 开始",
  "BicepsFlexedIcon": "Biceps Flexed",
  "BikeIcon": "Bike",
  "BinaryIcon": "二进制",
  "BinocularsIcon": "Binoculars",
  "BiohazardIcon": "生物危害",
  "BirdIcon": "鸟",
  "BirdhouseIcon": "Birdhouse",
  "BitcoinIcon": "比特币",
  "BlendIcon": "混合",
  "BlindsIcon": "百叶窗",
  "BlocksIcon": "积木",
  "BluetoothConnectedIcon": "蓝牙 已连接",
  "BluetoothIcon": "蓝牙",
  "BluetoothOffIcon": "蓝牙 关闭",
  "BluetoothSearchingIcon": "蓝牙 搜索中",
  "BoldIcon": "加粗",
  "BoltIcon": "螺栓",
  "BombIcon": "炸弹",
  "BoneIcon": "骨头",
  "BookAIcon": "书 A",
  "BookAlertIcon": "书 警告",
  "BookAudioIcon": "书 音频",
  "BookCheckIcon": "书 勾选",
  "BookCopyIcon": "书 复制",
  "BookDashedIcon": "书 虚线",
  "BookDownIcon": "书 下",
  "BookHeadphonesIcon": "书 耳机",
  "BookHeartIcon": "书 心",
  "BookIcon": "书",
  "BookImageIcon": "书 图片",
  "BookKeyIcon": "书 钥匙",
  "BookLockIcon": "书 锁定",
  "BookMarkedIcon": "书 Marked",
  "BookMinusIcon": "书 减",
  "BookOpenCheckIcon": "书 打开 勾选",
  "BookOpenIcon": "书 打开",
  "BookOpenTextIcon": "书 打开 文本",
  "BookPlusIcon": "书 加",
  "BookTemplateIcon": "书 模板",
  "BookTextIcon": "书 文本",
  "BookTypeIcon": "书 文字",
  "BookUp2Icon": "书 上 2",
  "BookUpIcon": "书 上",
  "BookUserIcon": "书 用户",
  "BookXIcon": "书 X",
  "BookmarkCheckIcon": "书签 勾选",
  "BookmarkIcon": "书签",
  "BookmarkMinusIcon": "书签 减",
  "BookmarkPlusIcon": "书签 加",
  "BookmarkXIcon": "书签 X",
  "BoomBoxIcon": "繁荣 盒子",
  "BotIcon": "机器人",
  "BotMessageSquareIcon": "机器人 消息 方块",
  "BotOffIcon": "机器人 关闭",
  "BottleWineIcon": "瓶 红酒",
  "BowArrowIcon": "Bow 箭头",
  "BoxIcon": "盒子",
  "BoxSelectIcon": "盒子 选择",
  "BoxesIcon": "多个盒子",
  "BracesIcon": "花括号",
  "BracketsIcon": "方括号",
  "BrainCircuitIcon": "大脑 电路",
  "BrainCogIcon": "大脑 齿轮",
  "BrainIcon": "大脑",
  "BrickWallFireIcon": "砖 墙 火",
  "BrickWallIcon": "砖 墙",
  "BrickWallShieldIcon": "砖 墙 盾牌",
  "BriefcaseBusinessIcon": "公文包 Business",
  "BriefcaseConveyorBeltIcon": "公文包 Conveyor Belt",
  "BriefcaseIcon": "公文包",
  "BriefcaseMedicalIcon": "公文包 Medical",
  "BringToFrontIcon": "Bring 到 前",
  "BrushCleaningIcon": "画笔 Cleaning",
  "BrushIcon": "画笔",
  "BubblesIcon": "Bubbles",
  "BugIcon": "虫",
  "BugOffIcon": "虫 关闭",
  "BugPlayIcon": "虫 播放",
  "Building2Icon": "楼房",
  "BuildingIcon": "建筑",
  "BusFrontIcon": "巴士 前",
  "BusIcon": "巴士",
  "CableCarIcon": "线缆 汽车",
  "CableIcon": "线缆",
  "CakeIcon": "蛋糕",
  "CakeSliceIcon": "蛋糕 切片",
  "CalculatorIcon": "计算器",
  "Calendar1Icon": "日历 1",
  "CalendarArrowDownIcon": "日历 箭头 下",
  "CalendarArrowUpIcon": "日历 箭头 上",
  "CalendarCheck2Icon": "日历 勾选 2",
  "CalendarCheckIcon": "日历 勾选",
  "CalendarClockIcon": "日历 时钟",
  "CalendarCogIcon": "日历 齿轮",
  "CalendarDaysIcon": "日历 天数",
  "CalendarFoldIcon": "日历 折叠",
  "CalendarHeartIcon": "日历 心",
  "CalendarIcon": "日历",
  "CalendarMinus2Icon": "日历 减 2",
  "CalendarMinusIcon": "日历 减",
  "CalendarOffIcon": "日历 关闭",
  "CalendarPlus2Icon": "日历 加 2",
  "CalendarPlusIcon": "日历 加",
  "CalendarRangeIcon": "日历 范围",
  "CalendarSearchIcon": "日历 搜索",
  "CalendarSyncIcon": "日历 同步",
  "CalendarX2Icon": "日历 X 2",
  "CalendarXIcon": "日历 X",
  "CalendarsIcon": "日历",
  "CameraIcon": "相机",
  "CameraOffIcon": "相机 关闭",
  "CandlestickChartIcon": "K线 图表",
  "CandyCaneIcon": "糖果 Cane",
  "CandyIcon": "糖果",
  "CandyOffIcon": "糖果 关闭",
  "CannabisIcon": "大麻",
  "CaptionsIcon": "字幕",
  "CaptionsOffIcon": "字幕 关闭",
  "CarFrontIcon": "汽车 前",
  "CarIcon": "汽车",
  "CarTaxiFrontIcon": "汽车 出租车 前",
  "CaravanIcon": "Caravan",
  "CardSimIcon": "卡片 Sim",
  "CarrotIcon": "胡萝卜",
  "CaseLowerIcon": "大小写 Lower",
  "CaseSensitiveIcon": "大小写 Sensitive",
  "CaseUpperIcon": "大小写 上",
  "CassetteTapeIcon": "Cassette Tape",
  "CastIcon": "投屏",
  "CastleIcon": "城堡",
  "CatIcon": "猫",
  "CctvIcon": "监控",
  "ChartAreaIcon": "图表 区域",
  "ChartBarBigIcon": "图表 条 大",
  "ChartBarDecreasingIcon": "图表 条 递减",
  "ChartBarIcon": "图表 条",
  "ChartBarIncreasingIcon": "图表 条 增长",
  "ChartBarStackedIcon": "图表 条 堆叠",
  "ChartCandlestickIcon": "图表 K线",
  "ChartColumnBigIcon": "图表 列 大",
  "ChartColumnDecreasingIcon": "图表 列 递减",
  "ChartColumnIcon": "图表 列",
  "ChartColumnIncreasingIcon": "图表 列 增长",
  "ChartColumnStackedIcon": "图表 列 堆叠",
  "ChartGanttIcon": "图表 甘特图",
  "ChartLineIcon": "图表 线",
  "ChartNetworkIcon": "图表 网络",
  "ChartNoAxesColumnDecreasingIcon": "图表 无 坐标轴 列 递减",
  "ChartNoAxesColumnIcon": "图表 无 坐标轴 列",
  "ChartNoAxesColumnIncreasingIcon": "图表 无 坐标轴 列 增长",
  "ChartNoAxesCombinedIcon": "图表 无 坐标轴 Combined",
  "ChartNoAxesGanttIcon": "图表 无 坐标轴 甘特图",
  "ChartPieIcon": "图表 饼图",
  "ChartScatterIcon": "图表 散布",
  "ChartSplineIcon": "图表 曲线",
  "CheckCheckIcon": "双勾选 已读",
  "CheckCircle2Icon": "勾选 圆 2",
  "CheckCircleIcon": "圆形勾选",
  "CheckIcon": "勾选 对号",
  "CheckLineIcon": "勾选 线",
  "CheckSquare2Icon": "勾选 方块 2",
  "CheckSquareIcon": "方块勾选",
  "ChefHatIcon": "Chef 帽子",
  "CherryIcon": "樱桃",
  "ChessBishopIcon": "国际象棋 Bishop",
  "ChessKingIcon": "国际象棋 King",
  "ChessKnightIcon": "国际象棋 Knight",
  "ChessPawnIcon": "国际象棋 Pawn",
  "ChessQueenIcon": "国际象棋 Queen",
  "ChessRookIcon": "国际象棋 Rook",
  "ChevronDownCircleIcon": "箭头 下 圆",
  "ChevronDownIcon": "向下箭头",
  "ChevronDownSquareIcon": "箭头 下 方块",
  "ChevronFirstIcon": "首页 跳到开始",
  "ChevronLastIcon": "末页 跳到结尾",
  "ChevronLeftCircleIcon": "箭头 左 圆",
  "ChevronLeftIcon": "向左箭头",
  "ChevronLeftSquareIcon": "箭头 左 方块",
  "ChevronRightCircleIcon": "箭头 右 圆",
  "ChevronRightIcon": "向右箭头",
  "ChevronRightSquareIcon": "箭头 右 方块",
  "ChevronUpCircleIcon": "箭头 上 圆",
  "ChevronUpIcon": "向上箭头",
  "ChevronUpSquareIcon": "箭头 上 方块",
  "ChevronsDownIcon": "双向下箭头",
  "ChevronsDownUpIcon": "上下双箭头",
  "ChevronsLeftIcon": "双向左箭头",
  "ChevronsLeftRightEllipsisIcon": "双箭头 左 右 省略",
  "ChevronsLeftRightIcon": "左右双箭头 收起",
  "ChevronsRightIcon": "双向右箭头",
  "ChevronsRightLeftIcon": "右左双箭头 展开",
  "ChevronsUpDownIcon": "上下双箭头",
  "ChevronsUpIcon": "双向上箭头",
  "ChromeIcon": "Chrome",
  "ChromiumIcon": "Chromium",
  "ChurchIcon": "教堂",
  "CigaretteIcon": "香烟",
  "CigaretteOffIcon": "香烟 关闭",
  "CircleAlertIcon": "警告 圆",
  "CircleArrowDownIcon": "下箭头 圆",
  "CircleArrowLeftIcon": "左箭头 圆",
  "CircleArrowOutDownLeftIcon": "圆 箭头 出 下 左",
  "CircleArrowOutDownRightIcon": "圆 箭头 出 下 右",
  "CircleArrowOutUpLeftIcon": "圆 箭头 出 上 左",
  "CircleArrowOutUpRightIcon": "圆 箭头 出 上 右",
  "CircleArrowRightIcon": "右箭头 圆",
  "CircleArrowUpIcon": "上箭头 圆",
  "CircleCheckBigIcon": "大勾选 圆",
  "CircleCheckIcon": "勾选 圆",
  "CircleChevronDownIcon": "圆 箭头 下",
  "CircleChevronLeftIcon": "圆 箭头 左",
  "CircleChevronRightIcon": "圆 箭头 右",
  "CircleChevronUpIcon": "圆 箭头 上",
  "CircleDashedIcon": "圆 虚线",
  "CircleDivideIcon": "圆 除",
  "CircleDollarSignIcon": "美元 圆",
  "CircleDotDashedIcon": "圆 点 虚线",
  "CircleDotIcon": "圆 点",
  "CircleEllipsisIcon": "更多 圆",
  "CircleEqualIcon": "圆 等号",
  "CircleFadingArrowUpIcon": "圆 淡入淡出 箭头 上",
  "CircleFadingPlusIcon": "圆 淡入淡出 加",
  "CircleGaugeIcon": "圆 仪表",
  "CircleHelpIcon": "帮助 问号",
  "CircleIcon": "圆",
  "CircleMinusIcon": "减号 圆",
  "CircleOffIcon": "圆 关闭",
  "CircleParkingIcon": "圆 停车",
  "CircleParkingOffIcon": "圆 停车 关闭",
  "CirclePauseIcon": "圆 暂停",
  "CirclePercentIcon": "圆 百分号",
  "CirclePlayIcon": "圆 播放",
  "CirclePlusIcon": "加号 圆",
  "CirclePoundSterlingIcon": "英镑 圆",
  "CirclePowerIcon": "圆 电源",
  "CircleQuestionMarkIcon": "圆 问号 标记",
  "CircleSlash2Icon": "禁止 圆",
  "CircleSlashIcon": "禁止 圆",
  "CircleSlashedIcon": "圆 Slashed",
  "CircleSmallIcon": "圆 小",
  "CircleStarIcon": "圆 星",
  "CircleStopIcon": "圆 停止",
  "CircleUserIcon": "用户 圆",
  "CircleUserRoundIcon": "用户头像 圆",
  "CircleXIcon": "关闭 圆",
  "CircuitBoardIcon": "电路 Board",
  "CitrusIcon": "柑橘",
  "ClapperboardIcon": "Clapperboard",
  "ClipboardCheckIcon": "剪贴板 勾选",
  "ClipboardClockIcon": "剪贴板 时钟",
  "ClipboardCopyIcon": "剪贴板 复制",
  "ClipboardEditIcon": "剪贴板 编辑",
  "ClipboardIcon": "剪贴板",
  "ClipboardListIcon": "剪贴板 列表",
  "ClipboardMinusIcon": "剪贴板 减",
  "ClipboardPasteIcon": "剪贴板 Paste",
  "ClipboardPenIcon": "剪贴板 钢笔",
  "ClipboardPenLineIcon": "剪贴板 钢笔 线",
  "ClipboardPlusIcon": "剪贴板 加",
  "ClipboardSignatureIcon": "剪贴板 签名",
  "ClipboardTypeIcon": "剪贴板 文字",
  "ClipboardXIcon": "剪贴板 X",
  "Clock10Icon": "时钟 10",
  "Clock11Icon": "时钟 11",
  "Clock12Icon": "时钟 12",
  "Clock1Icon": "时钟 1",
  "Clock2Icon": "时钟 2",
  "Clock3Icon": "时钟 3",
  "Clock4Icon": "时钟 4",
  "Clock5Icon": "时钟 5",
  "Clock6Icon": "时钟 6",
  "Clock7Icon": "时钟 7",
  "Clock8Icon": "时钟 8",
  "Clock9Icon": "时钟 9",
  "ClockAlertIcon": "时钟 警告",
  "ClockArrowDownIcon": "时钟 箭头 下",
  "ClockArrowUpIcon": "时钟 箭头 上",
  "ClockCheckIcon": "时钟 勾选",
  "ClockFadingIcon": "时钟 淡入淡出",
  "ClockIcon": "时钟",
  "ClockPlusIcon": "时钟 加",
  "ClosedCaptionIcon": "已关闭 Caption",
  "CloudAlertIcon": "云 警告",
  "CloudCheckIcon": "云 勾选",
  "CloudCogIcon": "云 齿轮",
  "CloudDownloadIcon": "云 下载",
  "CloudDrizzleIcon": "云 Drizzle",
  "CloudFogIcon": "云 Fog",
  "CloudHailIcon": "云 Hail",
  "CloudIcon": "云",
  "CloudLightningIcon": "云 闪电",
  "CloudMoonIcon": "云 月亮",
  "CloudMoonRainIcon": "云 月亮 雨",
  "CloudOffIcon": "云 关闭",
  "CloudRainIcon": "云 雨",
  "CloudRainWindIcon": "云 雨 风",
  "CloudSnowIcon": "云 雪",
  "CloudSunIcon": "云 太阳",
  "CloudSunRainIcon": "云 太阳 雨",
  "CloudUploadIcon": "云 上传",
  "CloudyIcon": "多云",
  "CloverIcon": "三叶草",
  "ClubIcon": "梅花",
  "Code2Icon": "代码",
  "CodeIcon": "代码 尖括号",
  "CodeSquareIcon": "代码 方块",
  "CodeXmlIcon": "代码 XML",
  "CodepenIcon": "Codepen",
  "CodesandboxIcon": "Codesandbox",
  "CoffeeIcon": "咖啡",
  "CogIcon": "齿轮",
  "CoinsIcon": "硬币",
  "Columns2Icon": "列 2",
  "Columns3CogIcon": "列 3 齿轮",
  "Columns3Icon": "列 3",
  "Columns4Icon": "列 4",
  "ColumnsIcon": "列",
  "ColumnsSettingsIcon": "列 设置",
  "CombineIcon": "合并",
  "CommandIcon": "命令键",
  "CompassIcon": "指南针",
  "ComponentIcon": "组件",
  "ComputerIcon": "电脑",
  "ConciergeBellIcon": "前台 铃铛 通知",
  "ConeIcon": "圆锥",
  "ConstructionIcon": "施工",
  "Contact2Icon": "联系人 2",
  "ContactIcon": "联系人",
  "ContactRoundIcon": "联系人 圆",
  "ContainerIcon": "容器",
  "ContrastIcon": "对比度",
  "CookieIcon": "饼干",
  "CookingPotIcon": "Cooking Pot",
  "CopyCheckIcon": "复制 勾选",
  "CopyIcon": "复制",
  "CopyMinusIcon": "复制 减",
  "CopyPlusIcon": "复制 加",
  "CopySlashIcon": "复制 斜杠",
  "CopyXIcon": "复制 X",
  "CopyleftIcon": "Copyleft",
  "CopyrightIcon": "Copyright",
  "CornerDownLeftIcon": "回车 左下转角",
  "CornerDownRightIcon": "右下转角",
  "CornerLeftDownIcon": "左下转角",
  "CornerLeftUpIcon": "左上转角",
  "CornerRightDownIcon": "右下转角",
  "CornerRightUpIcon": "右上转角",
  "CornerUpLeftIcon": "左上转角",
  "CornerUpRightIcon": "右上转角",
  "CpuIcon": "CPU",
  "CreativeCommonsIcon": "Creative Commons",
  "CreditCardIcon": "信用 卡片",
  "CroissantIcon": "牛角包",
  "CropIcon": "裁剪",
  "CrossIcon": "十字",
  "CrosshairIcon": "十字准线",
  "CrownIcon": "皇冠",
  "CuboidIcon": "立方体",
  "CupSodaIcon": "杯子 Soda",
  "CurlyBracesIcon": "Curly 花括号",
  "CurrencyIcon": "货币",
  "CylinderIcon": "圆柱",
  "DamIcon": "水坝",
  "DatabaseBackupIcon": "数据库 Backup",
  "DatabaseIcon": "数据库",
  "DatabaseZapIcon": "数据库 闪电",
  "DecimalsArrowLeftIcon": "小数 箭头 左",
  "DecimalsArrowRightIcon": "小数 箭头 右",
  "DeleteIcon": "删除",
  "DessertIcon": "甜点",
  "DiameterIcon": "直径",
  "DiamondIcon": "钻石",
  "DiamondMinusIcon": "钻石 减",
  "DiamondPercentIcon": "钻石 百分号",
  "DiamondPlusIcon": "钻石 加",
  "Dice1Icon": "骰子 1",
  "Dice2Icon": "骰子 2",
  "Dice3Icon": "骰子 3",
  "Dice4Icon": "骰子 4",
  "Dice5Icon": "骰子 5",
  "Dice6Icon": "骰子 6",
  "DicesIcon": "Dices",
  "DiffIcon": "差异",
  "Disc2Icon": "光盘 2",
  "Disc3Icon": "光盘 3",
  "DiscAlbumIcon": "光盘 相册",
  "DiscIcon": "光盘",
  "DivideCircleIcon": "除 圆",
  "DivideIcon": "除号",
  "DivideSquareIcon": "除 方块",
  "DnaIcon": "DNA",
  "DnaOffIcon": "DNA 关闭",
  "DockIcon": "船坞",
  "DogIcon": "狗",
  "DollarSignIcon": "美元 符号",
  "DonutIcon": "甜甜圈",
  "DoorClosedIcon": "门 已关闭",
  "DoorClosedLockedIcon": "门 已关闭 Locked",
  "DoorOpenIcon": "门 打开",
  "DotIcon": "点",
  "DotSquareIcon": "点 方块",
  "DownloadCloudIcon": "下载 云",
  "DownloadIcon": "下载",
  "DraftingCompassIcon": "绘图 指南针",
  "DramaIcon": "Drama",
  "DribbbleIcon": "Dribbble",
  "DrillIcon": "钻",
  "DroneIcon": "Drone",
  "DropletIcon": "水滴",
  "DropletOffIcon": "水滴 关闭",
  "DropletsIcon": "水滴",
  "DrumIcon": "鼓",
  "DrumstickIcon": "鸡腿",
  "DumbbellIcon": "哑铃",
  "EarIcon": "耳朵",
  "EarOffIcon": "耳朵 关闭",
  "EarthIcon": "地球",
  "EarthLockIcon": "地球 锁定",
  "EclipseIcon": "Eclipse",
  "Edit2Icon": "编辑 2",
  "Edit3Icon": "编辑 3",
  "EditIcon": "编辑",
  "EggFriedIcon": "鸡蛋 Fried",
  "EggIcon": "鸡蛋",
  "EggOffIcon": "鸡蛋 关闭",
  "EllipsisIcon": "更多 三点",
  "EllipsisVerticalIcon": "更多 竖三点",
  "EqualApproximatelyIcon": "等号 Approximately",
  "EqualIcon": "等号",
  "EqualNotIcon": "不等号",
  "EqualSquareIcon": "等号 方块",
  "EraserIcon": "橡皮",
  "EthernetPortIcon": "Ethernet 端口",
  "EuroIcon": "欧元",
  "EvChargerIcon": "Ev Charger",
  "ExpandIcon": "展开",
  "ExternalLinkIcon": "外部 链接",
  "EyeClosedIcon": "眼睛闭上 隐藏",
  "EyeIcon": "眼睛 查看",
  "EyeOffIcon": "隐藏 眼睛关闭",
  "FacebookIcon": "Facebook",
  "FactoryIcon": "工厂",
  "FanIcon": "风扇",
  "FastForwardIcon": "Fast 前进",
  "FeatherIcon": "羽毛",
  "FenceIcon": "栅栏",
  "FerrisWheelIcon": "摩天轮 轮",
  "FigmaIcon": "Figma",
  "FileArchiveIcon": "文件 归档",
  "FileAudio2Icon": "文件 音频 2",
  "FileAudioIcon": "文件 音频",
  "FileAxis3DIcon": "文件 轴 3 D",
  "FileAxis3dIcon": "文件 轴 3 D",
  "FileBadge2Icon": "文件 徽章 2",
  "FileBadgeIcon": "文件 徽章",
  "FileBarChart2Icon": "文件 条 图表 2",
  "FileBarChartIcon": "文件 条 图表",
  "FileBoxIcon": "文件 盒子",
  "FileBracesCornerIcon": "文件 花括号 转角",
  "FileBracesIcon": "文件 花括号",
  "FileChartColumnIcon": "文件 图表 列",
  "FileChartColumnIncreasingIcon": "文件 图表 列 增长",
  "FileChartLineIcon": "文件 图表 线",
  "FileChartPieIcon": "文件 图表 饼图",
  "FileCheck2Icon": "文件 勾选 2",
  "FileCheckCornerIcon": "文件 勾选 转角",
  "FileCheckIcon": "文件 勾选",
  "FileClockIcon": "文件 时钟",
  "FileCode2Icon": "文件 代码 2",
  "FileCodeCornerIcon": "文件 代码 转角",
  "FileCodeIcon": "文件 代码",
  "FileCog2Icon": "文件 齿轮 2",
  "FileCogIcon": "文件 齿轮",
  "FileDiffIcon": "文件 差异",
  "FileDigitIcon": "文件 Digit",
  "FileDownIcon": "文件 下",
  "FileEditIcon": "文件 编辑",
  "FileExclamationPointIcon": "文件 Exclamation Point",
  "FileHeadphoneIcon": "文件 耳机",
  "FileHeartIcon": "文件 心",
  "FileIcon": "文件",
  "FileImageIcon": "文件 图片",
  "FileInputIcon": "文件 输入",
  "FileJson2Icon": "文件 JSON 2",
  "FileJsonIcon": "文件 JSON",
  "FileKey2Icon": "文件 钥匙 2",
  "FileKeyIcon": "文件 钥匙",
  "FileLineChartIcon": "文件 线 图表",
  "FileLock2Icon": "文件 锁定 2",
  "FileLockIcon": "文件 锁定",
  "FileMinus2Icon": "文件 减 2",
  "FileMinusCornerIcon": "文件 减 转角",
  "FileMinusIcon": "文件 减",
  "FileMusicIcon": "文件 音乐",
  "FileOutputIcon": "文件 输出",
  "FilePenIcon": "文件 钢笔",
  "FilePenLineIcon": "文件 钢笔 线",
  "FilePieChartIcon": "文件 饼图 图表",
  "FilePlayIcon": "文件 播放",
  "FilePlus2Icon": "文件 加 2",
  "FilePlusCornerIcon": "文件 加 转角",
  "FilePlusIcon": "文件 加",
  "FileQuestionIcon": "文件 问号",
  "FileQuestionMarkIcon": "文件 问号 标记",
  "FileScanIcon": "文件 扫描",
  "FileSearch2Icon": "文件 搜索 2",
  "FileSearchCornerIcon": "文件 搜索 转角",
  "FileSearchIcon": "文件 搜索",
  "FileSignalIcon": "文件 信号",
  "FileSignatureIcon": "文件 签名",
  "FileSlidersIcon": "文件 滑块",
  "FileSpreadsheetIcon": "文件 Spreadsheet",
  "FileStackIcon": "文件 栈",
  "FileSymlinkIcon": "文件 软链",
  "FileTerminalIcon": "文件 终端",
  "FileTextIcon": "文件 文本",
  "FileType2Icon": "文件 文字 2",
  "FileTypeCornerIcon": "文件 文字 转角",
  "FileTypeIcon": "文件 文字",
  "FileUpIcon": "文件 上",
  "FileUserIcon": "文件 用户",
  "FileVideo2Icon": "文件 视频 2",
  "FileVideoCameraIcon": "文件 视频 相机",
  "FileVideoIcon": "文件 视频",
  "FileVolume2Icon": "文件 音量 2",
  "FileVolumeIcon": "文件 音量",
  "FileWarningIcon": "文件 警告",
  "FileX2Icon": "文件 X 2",
  "FileXCornerIcon": "文件 X 转角",
  "FileXIcon": "文件 X",
  "FilesIcon": "多文件",
  "FilmIcon": "胶片",
  "FilterIcon": "筛选",
  "FilterXIcon": "筛选 X",
  "FingerprintIcon": "指纹",
  "FingerprintPatternIcon": "指纹 Pattern",
  "FireExtinguisherIcon": "火 Extinguisher",
  "FishIcon": "鱼",
  "FishOffIcon": "鱼 关闭",
  "FishSymbolIcon": "鱼 符号",
  "FlagIcon": "旗帜",
  "FlagOffIcon": "旗帜 关闭",
  "FlagTriangleLeftIcon": "旗帜 三角形 左",
  "FlagTriangleRightIcon": "旗帜 三角形 右",
  "FlameIcon": "火焰",
  "FlameKindlingIcon": "火焰 Kindling",
  "FlashlightIcon": "手电筒",
  "FlashlightOffIcon": "手电筒 关闭",
  "FlaskConicalIcon": "烧瓶 圆锥",
  "FlaskConicalOffIcon": "烧瓶 圆锥 关闭",
  "FlaskRoundIcon": "烧瓶 圆",
  "FlipHorizontal2Icon": "翻转 水平 2",
  "FlipHorizontalIcon": "翻转 水平",
  "FlipVertical2Icon": "翻转 垂直 2",
  "FlipVerticalIcon": "翻转 垂直",
  "Flower2Icon": "花 2",
  "FlowerIcon": "花",
  "FocusIcon": "聚焦",
  "FoldHorizontalIcon": "折叠 水平",
  "FoldVerticalIcon": "折叠 垂直",
  "FolderArchiveIcon": "文件夹 归档",
  "FolderCheckIcon": "文件夹 勾选",
  "FolderClockIcon": "文件夹 时钟",
  "FolderClosedIcon": "文件夹 已关闭",
  "FolderCodeIcon": "文件夹 代码",
  "FolderCog2Icon": "文件夹 齿轮 2",
  "FolderCogIcon": "文件夹 齿轮",
  "FolderDotIcon": "文件夹 点",
  "FolderDownIcon": "文件夹 下",
  "FolderEditIcon": "文件夹 编辑",
  "FolderGit2Icon": "文件夹 Git 2",
  "FolderGitIcon": "文件夹 Git",
  "FolderHeartIcon": "文件夹 心",
  "FolderIcon": "文件夹",
  "FolderInputIcon": "文件夹 输入",
  "FolderKanbanIcon": "文件夹 看板",
  "FolderKeyIcon": "文件夹 钥匙",
  "FolderLockIcon": "文件夹 锁定",
  "FolderMinusIcon": "文件夹 减",
  "FolderOpenDotIcon": "文件夹 打开 点",
  "FolderOpenIcon": "文件夹 打开",
  "FolderOutputIcon": "文件夹 输出",
  "FolderPenIcon": "文件夹 钢笔",
  "FolderPlusIcon": "文件夹 加",
  "FolderRootIcon": "文件夹 Root",
  "FolderSearch2Icon": "文件夹 搜索 2",
  "FolderSearchIcon": "文件夹 搜索",
  "FolderSymlinkIcon": "文件夹 软链",
  "FolderSyncIcon": "文件夹 同步",
  "FolderTreeIcon": "文件夹 树",
  "FolderUpIcon": "文件夹 上",
  "FolderXIcon": "文件夹 X",
  "FoldersIcon": "多文件夹",
  "FootprintsIcon": "脚印",
  "ForkKnifeCrossedIcon": "叉 刀 交叉",
  "ForkKnifeIcon": "叉 刀",
  "ForkliftIcon": "叉车",
  "FormIcon": "表单",
  "FormInputIcon": "表单 输入",
  "ForwardIcon": "前进",
  "FrameIcon": "边框",
  "FramerIcon": "Framer",
  "FrownIcon": "皱眉",
  "FuelIcon": "燃料",
  "FullscreenIcon": "Fullscreen",
  "FunctionSquareIcon": "函数 方块",
  "FunnelIcon": "漏斗",
  "FunnelPlusIcon": "漏斗 加",
  "FunnelXIcon": "漏斗 X",
  "GalleryHorizontalEndIcon": "画廊 水平 末",
  "GalleryHorizontalIcon": "画廊 水平",
  "GalleryThumbnailsIcon": "画廊 Thumbnails",
  "GalleryVerticalEndIcon": "画廊 垂直 末",
  "GalleryVerticalIcon": "画廊 垂直",
  "Gamepad2Icon": "游戏手柄 2",
  "GamepadDirectionalIcon": "游戏手柄 Directional",
  "GamepadIcon": "游戏手柄",
  "GanttChartIcon": "甘特图 图表",
  "GanttChartSquareIcon": "甘特图 图表 方块",
  "GaugeCircleIcon": "仪表 圆",
  "GaugeIcon": "仪表",
  "GavelIcon": "法槌",
  "GemIcon": "宝石",
  "GeorgianLariIcon": "Georgian Lari",
  "GhostIcon": "幽灵",
  "GiftIcon": "礼物",
  "GitBranchIcon": "Git 分支",
  "GitBranchMinusIcon": "Git 分支 减",
  "GitBranchPlusIcon": "Git 分支 加",
  "GitCommitHorizontalIcon": "Git 提交 水平",
  "GitCommitIcon": "Git 提交",
  "GitCommitVerticalIcon": "Git 提交 垂直",
  "GitCompareArrowsIcon": "Git 对比 箭头",
  "GitCompareIcon": "Git 对比",
  "GitForkIcon": "Git 叉",
  "GitGraphIcon": "Git Graph",
  "GitMergeIcon": "Git 合并",
  "GitPullRequestArrowIcon": "Git 拉取 请求 箭头",
  "GitPullRequestClosedIcon": "Git 拉取 请求 已关闭",
  "GitPullRequestCreateArrowIcon": "Git 拉取 请求 创建 箭头",
  "GitPullRequestCreateIcon": "Git 拉取 请求 创建",
  "GitPullRequestDraftIcon": "Git 拉取 请求 Draft",
  "GitPullRequestIcon": "Git 拉取 请求",
  "GithubIcon": "Github",
  "GitlabIcon": "Gitlab",
  "GlassWaterIcon": "玻璃 水",
  "GlassesIcon": "眼镜",
  "Globe2Icon": "地球 2",
  "GlobeIcon": "地球",
  "GlobeLockIcon": "地球 锁定",
  "GoalIcon": "目标",
  "GpuIcon": "Gpu",
  "GrabIcon": "抓取",
  "GraduationCapIcon": "毕业 Cap",
  "GrapeIcon": "葡萄",
  "Grid2X2CheckIcon": "网格 2 X 2 勾选",
  "Grid2X2Icon": "网格 2 X 2",
  "Grid2X2PlusIcon": "网格 2 X 2 加",
  "Grid2X2XIcon": "网格 2 X 2 X",
  "Grid2x2CheckIcon": "网格 2 X 2 勾选",
  "Grid2x2Icon": "网格 2 X 2",
  "Grid2x2PlusIcon": "网格 2 X 2 加",
  "Grid2x2XIcon": "网格 2 X 2 X",
  "Grid3X3Icon": "网格 3 X 3",
  "Grid3x2Icon": "网格 3 X 2",
  "Grid3x3Icon": "网格 3 X 3",
  "GridIcon": "网格",
  "GripHorizontalIcon": "把手 水平",
  "GripIcon": "把手",
  "GripVerticalIcon": "把手 垂直",
  "GroupIcon": "组",
  "GuitarIcon": "吉他",
  "HamIcon": "火腿",
  "HamburgerIcon": "Hamburger",
  "HammerIcon": "锤",
  "HandCoinsIcon": "手 硬币",
  "HandFistIcon": "手 Fist",
  "HandGrabIcon": "手 抓取",
  "HandHeartIcon": "手 心",
  "HandHelpingIcon": "手 帮助",
  "HandIcon": "手",
  "HandMetalIcon": "手 Metal",
  "HandPlatterIcon": "手 托盘",
  "HandbagIcon": "Handbag",
  "HandshakeIcon": "握手",
  "HardDriveDownloadIcon": "硬 驱动 下载",
  "HardDriveIcon": "硬 驱动",
  "HardDriveUploadIcon": "硬 驱动 上传",
  "HardHatIcon": "硬 帽子",
  "HashIcon": "井号 #",
  "HatGlassesIcon": "帽子 眼镜",
  "HazeIcon": "薄雾",
  "HdmiPortIcon": "HDMI 端口",
  "Heading1Icon": "标题 1",
  "Heading2Icon": "标题 2",
  "Heading3Icon": "标题 3",
  "Heading4Icon": "标题 4",
  "Heading5Icon": "标题 5",
  "Heading6Icon": "标题 6",
  "HeadingIcon": "标题",
  "HeadphoneOffIcon": "耳机 关闭",
  "HeadphonesIcon": "耳机",
  "HeadsetIcon": "头戴耳机",
  "HeartCrackIcon": "心 裂",
  "HeartHandshakeIcon": "心 握手",
  "HeartIcon": "心",
  "HeartMinusIcon": "心 减",
  "HeartOffIcon": "心 关闭",
  "HeartPlusIcon": "心 加",
  "HeartPulseIcon": "心 跳动",
  "HeaterIcon": "加热器",
  "HelicopterIcon": "Helicopter",
  "HelpCircleIcon": "帮助 问号",
  "HelpingHandIcon": "帮助 手",
  "HexagonIcon": "六边形",
  "HighlighterIcon": "荧光笔",
  "HistoryIcon": "历史",
  "HomeIcon": "主页 房子",
  "HopIcon": "啤酒花",
  "HopOffIcon": "啤酒花 关闭",
  "HospitalIcon": "医院",
  "HotelIcon": "酒店",
  "HourglassIcon": "沙漏",
  "HouseHeartIcon": "房子 心",
  "HouseIcon": "房子",
  "HousePlugIcon": "房子 插头",
  "HousePlusIcon": "房子 加",
  "HouseWifiIcon": "房子 WiFi",
  "IceCream2Icon": "冰淇淋",
  "IceCreamBowlIcon": "冰 奶油 Bowl",
  "IceCreamConeIcon": "冰淇淋蛋筒",
  "IceCreamIcon": "冰 奶油",
  "IdCardIcon": "ID 卡片",
  "IdCardLanyardIcon": "ID 卡片 Lanyard",
  "ImageDownIcon": "图片 下",
  "ImageIcon": "图片",
  "ImageMinusIcon": "图片 减",
  "ImageOffIcon": "图片 关闭",
  "ImagePlayIcon": "图片 播放",
  "ImagePlusIcon": "图片 加",
  "ImageUpIcon": "图片 上",
  "ImageUpscaleIcon": "图片 放大",
  "ImagesIcon": "多图片",
  "ImportIcon": "导入",
  "InboxIcon": "收件箱",
  "IndentDecreaseIcon": "缩进 减少",
  "IndentIcon": "缩进",
  "IndentIncreaseIcon": "缩进 增加",
  "IndianRupeeIcon": "印度 卢比",
  "InfinityIcon": "无限",
  "InfoIcon": "信息 i",
  "InspectIcon": "检查",
  "InspectionPanelIcon": "Inspection 面板",
  "InstagramIcon": "Instagram",
  "ItalicIcon": "斜体",
  "IterationCcwIcon": "迭代 逆时针",
  "IterationCwIcon": "迭代 顺时针",
  "JapaneseYenIcon": "日元",
  "JoystickIcon": "摇杆",
  "KanbanIcon": "看板",
  "KanbanSquareDashedIcon": "看板 方块 虚线",
  "KanbanSquareIcon": "看板 方块",
  "KayakIcon": "Kayak",
  "KeyIcon": "钥匙",
  "KeyRoundIcon": "圆头钥匙",
  "KeySquareIcon": "方头钥匙",
  "KeyboardIcon": "键盘",
  "KeyboardMusicIcon": "键盘 音乐",
  "KeyboardOffIcon": "键盘 关闭",
  "LampCeilingIcon": "灯 Ceiling",
  "LampDeskIcon": "灯 Desk",
  "LampFloorIcon": "灯 Floor",
  "LampIcon": "灯",
  "LampWallDownIcon": "灯 墙 下",
  "LampWallUpIcon": "灯 墙 上",
  "LandPlotIcon": "Land Plot",
  "LandmarkIcon": "地标",
  "LanguagesIcon": "语言",
  "Laptop2Icon": "笔记本 2",
  "LaptopIcon": "笔记本",
  "LaptopMinimalCheckIcon": "笔记本 极简 勾选",
  "LaptopMinimalIcon": "笔记本 极简",
  "LassoIcon": "套索",
  "LassoSelectIcon": "套索 选择",
  "LaughIcon": "大笑",
  "Layers2Icon": "图层 2",
  "Layers3Icon": "图层 3",
  "LayersIcon": "图层",
  "LayoutDashboardIcon": "布局 Dashboard",
  "LayoutGridIcon": "布局 网格",
  "LayoutIcon": "布局",
  "LayoutListIcon": "布局 列表",
  "LayoutPanelLeftIcon": "布局 面板 左",
  "LayoutPanelTopIcon": "布局 面板 顶",
  "LayoutTemplateIcon": "布局 模板",
  "LeafIcon": "叶",
  "LeafyGreenIcon": "多叶 Green",
  "LecternIcon": "Lectern",
  "LetterTextIcon": "Letter 文本",
  "LibraryBigIcon": "图书馆 大",
  "LibraryIcon": "图书馆",
  "LibrarySquareIcon": "图书馆 方块",
  "LifeBuoyIcon": "Life Buoy",
  "LigatureIcon": "Ligature",
  "LightbulbIcon": "灯泡",
  "LightbulbOffIcon": "灯泡 关闭",
  "LineChartIcon": "线 图表",
  "LineSquiggleIcon": "线 Squiggle",
  "Link2Icon": "链接 2",
  "Link2OffIcon": "链接 2 关闭",
  "LinkIcon": "链接",
  "LinkedinIcon": "LinkedIn",
  "ListCheckIcon": "列表 勾选",
  "ListChecksIcon": "列表 Checks",
  "ListChevronsDownUpIcon": "列表 双箭头 下 上",
  "ListChevronsUpDownIcon": "列表 双箭头 上 下",
  "ListCollapseIcon": "列表 Collapse",
  "ListEndIcon": "列表 末",
  "ListFilterIcon": "列表 筛选",
  "ListFilterPlusIcon": "列表 筛选 加",
  "ListIcon": "列表",
  "ListIndentDecreaseIcon": "列表 缩进 减少",
  "ListIndentIncreaseIcon": "列表 缩进 增加",
  "ListMinusIcon": "列表 减",
  "ListMusicIcon": "列表 音乐",
  "ListOrderedIcon": "列表 Ordered",
  "ListPlusIcon": "列表 加",
  "ListRestartIcon": "列表 Restart",
  "ListStartIcon": "列表 开始",
  "ListTodoIcon": "列表 Todo",
  "ListTreeIcon": "列表 树",
  "ListVideoIcon": "列表 视频",
  "ListXIcon": "列表 X",
  "Loader2Icon": "加载中 旋转",
  "LoaderCircleIcon": "加载中 圆",
  "LoaderIcon": "加载中",
  "LoaderPinwheelIcon": "加载中 风车",
  "LocateFixedIcon": "定位 Fixed",
  "LocateIcon": "定位",
  "LocateOffIcon": "定位 关闭",
  "LocationEditIcon": "位置 编辑",
  "LockIcon": "锁",
  "LockKeyholeIcon": "锁孔",
  "LockKeyholeOpenIcon": "开锁",
  "LockOpenIcon": "开锁",
  "LogInIcon": "登录",
  "LogOutIcon": "登出",
  "LogsIcon": "日志",
  "LollipopIcon": "Lollipop",
  "LuggageIcon": "Luggage",
  "MSquareIcon": "M 方块",
  "MagnetIcon": "Magnet",
  "MailCheckIcon": "邮件 勾选",
  "MailIcon": "邮件 信封",
  "MailMinusIcon": "邮件 减",
  "MailOpenIcon": "邮件 打开",
  "MailPlusIcon": "邮件 加",
  "MailQuestionIcon": "邮件 问号",
  "MailQuestionMarkIcon": "邮件 问号 标记",
  "MailSearchIcon": "邮件 搜索",
  "MailWarningIcon": "邮件 警告",
  "MailXIcon": "邮件 X",
  "MailboxIcon": "Mailbox",
  "MailsIcon": "多封邮件",
  "MapIcon": "地图",
  "MapMinusIcon": "地图 减",
  "MapPinCheckIcon": "地图 大头针 勾选",
  "MapPinCheckInsideIcon": "地图 大头针 勾选 内",
  "MapPinHouseIcon": "地图 大头针 房子",
  "MapPinIcon": "地图 大头针",
  "MapPinMinusIcon": "地图 大头针 减",
  "MapPinMinusInsideIcon": "地图 大头针 减 内",
  "MapPinOffIcon": "地图 大头针 关闭",
  "MapPinPenIcon": "地图 大头针 钢笔",
  "MapPinPlusIcon": "地图 大头针 加",
  "MapPinPlusInsideIcon": "地图 大头针 加 内",
  "MapPinXIcon": "地图 大头针 X",
  "MapPinXInsideIcon": "地图 大头针 X 内",
  "MapPinnedIcon": "地图 Pinned",
  "MapPlusIcon": "地图 加",
  "MarsIcon": "火星",
  "MarsStrokeIcon": "火星 Stroke",
  "MartiniIcon": "马提尼",
  "Maximize2Icon": "最大化 2",
  "MaximizeIcon": "最大化",
  "MedalIcon": "奖牌",
  "MegaphoneIcon": "喇叭",
  "MegaphoneOffIcon": "喇叭 关闭",
  "MehIcon": "平淡",
  "MemoryStickIcon": "Memory Stick",
  "MenuIcon": "菜单",
  "MenuSquareIcon": "菜单 方块",
  "MergeIcon": "合并",
  "MessageCircleCodeIcon": "消息 圆 代码",
  "MessageCircleDashedIcon": "消息 圆 虚线",
  "MessageCircleHeartIcon": "消息 圆 心",
  "MessageCircleIcon": "消息 圆",
  "MessageCircleMoreIcon": "消息 圆 更多",
  "MessageCircleOffIcon": "消息 圆 关闭",
  "MessageCirclePlusIcon": "消息 圆 加",
  "MessageCircleQuestionIcon": "消息 圆 问号",
  "MessageCircleQuestionMarkIcon": "消息 圆 问号 标记",
  "MessageCircleReplyIcon": "消息 圆 回复",
  "MessageCircleWarningIcon": "消息 圆 警告",
  "MessageCircleXIcon": "消息 圆 X",
  "MessageSquareCodeIcon": "消息 方块 代码",
  "MessageSquareDashedIcon": "消息 方块 虚线",
  "MessageSquareDiffIcon": "消息 方块 差异",
  "MessageSquareDotIcon": "消息 方块 点",
  "MessageSquareHeartIcon": "消息 方块 心",
  "MessageSquareIcon": "消息 方块",
  "MessageSquareLockIcon": "消息 方块 锁定",
  "MessageSquareMoreIcon": "消息 方块 更多",
  "MessageSquareOffIcon": "消息 方块 关闭",
  "MessageSquarePlusIcon": "消息 方块 加",
  "MessageSquareQuoteIcon": "消息 方块 引用",
  "MessageSquareReplyIcon": "消息 方块 回复",
  "MessageSquareShareIcon": "消息 方块 分享",
  "MessageSquareTextIcon": "消息 方块 文本",
  "MessageSquareWarningIcon": "消息 方块 警告",
  "MessageSquareXIcon": "消息 方块 X",
  "MessagesSquareIcon": "消息 方块",
  "Mic2Icon": "麦克风 2",
  "MicIcon": "麦克风",
  "MicOffIcon": "麦克风 关闭",
  "MicVocalIcon": "麦克风 人声",
  "MicrochipIcon": "Microchip",
  "MicroscopeIcon": "显微镜",
  "MicrowaveIcon": "微波炉",
  "MilestoneIcon": "里程碑",
  "MilkIcon": "牛奶",
  "MilkOffIcon": "牛奶 关闭",
  "Minimize2Icon": "最小化 2",
  "MinimizeIcon": "最小化",
  "MinusCircleIcon": "减 圆",
  "MinusIcon": "减号",
  "MinusSquareIcon": "减 方块",
  "MonitorCheckIcon": "显示器 勾选",
  "MonitorCloudIcon": "显示器 云",
  "MonitorCogIcon": "显示器 齿轮",
  "MonitorDotIcon": "显示器 点",
  "MonitorDownIcon": "显示器 下",
  "MonitorIcon": "显示器",
  "MonitorOffIcon": "显示器 关闭",
  "MonitorPauseIcon": "显示器 暂停",
  "MonitorPlayIcon": "显示器 播放",
  "MonitorSmartphoneIcon": "显示器 智能手机",
  "MonitorSpeakerIcon": "显示器 扬声器",
  "MonitorStopIcon": "显示器 停止",
  "MonitorUpIcon": "显示器 上",
  "MonitorXIcon": "显示器 X",
  "MoonIcon": "月亮 暗色模式",
  "MoonStarIcon": "月亮 星 暗色模式",
  "MoreHorizontalIcon": "更多 水平",
  "MoreVerticalIcon": "更多 垂直",
  "MotorbikeIcon": "Motorbike",
  "MountainIcon": "山",
  "MountainSnowIcon": "山 雪",
  "MouseIcon": "鼠标",
  "MouseOffIcon": "鼠标 关闭",
  "MousePointer2Icon": "鼠标 指针 2",
  "MousePointer2OffIcon": "鼠标 指针 2 关闭",
  "MousePointerBanIcon": "鼠标 指针 禁止",
  "MousePointerClickIcon": "鼠标 指针 Click",
  "MousePointerIcon": "鼠标 指针",
  "MousePointerSquareDashedIcon": "鼠标 指针 方块 虚线",
  "Move3DIcon": "移动 3 D",
  "Move3dIcon": "移动 3 D",
  "MoveDiagonal2Icon": "对角线移动",
  "MoveDiagonalIcon": "对角线移动",
  "MoveDownIcon": "向下移动",
  "MoveDownLeftIcon": "移动 下 左",
  "MoveDownRightIcon": "移动 下 右",
  "MoveHorizontalIcon": "水平移动",
  "MoveIcon": "移动",
  "MoveLeftIcon": "向左移动",
  "MoveRightIcon": "向右移动",
  "MoveUpIcon": "向上移动",
  "MoveUpLeftIcon": "移动 上 左",
  "MoveUpRightIcon": "移动 上 右",
  "MoveVerticalIcon": "垂直移动",
  "Music2Icon": "音乐 2",
  "Music3Icon": "音乐 3",
  "Music4Icon": "音乐 4",
  "MusicIcon": "音乐",
  "Navigation2Icon": "导航 2",
  "Navigation2OffIcon": "导航 2 关闭",
  "NavigationIcon": "导航",
  "NavigationOffIcon": "导航 关闭",
  "NetworkIcon": "网络",
  "NewspaperIcon": "报纸",
  "NfcIcon": "NFC",
  "NonBinaryIcon": "Non 二进制",
  "NotebookIcon": "笔记本",
  "NotebookPenIcon": "笔记本 钢笔",
  "NotebookTabsIcon": "笔记本 标签页",
  "NotebookTextIcon": "笔记本 文本",
  "NotepadTextDashedIcon": "记事本 文本 虚线",
  "NotepadTextIcon": "记事本 文本",
  "NutIcon": "螺母",
  "NutOffIcon": "螺母 关闭",
  "OctagonAlertIcon": "警告 八角",
  "OctagonIcon": "八边形",
  "OctagonMinusIcon": "八边形 减",
  "OctagonPauseIcon": "八边形 暂停",
  "OctagonXIcon": "八边形 X",
  "OmegaIcon": "欧米茄",
  "OptionIcon": "选项",
  "OrbitIcon": "轨道",
  "OrigamiIcon": "折纸",
  "OutdentIcon": "Outdent",
  "Package2Icon": "包裹 2",
  "PackageCheckIcon": "包裹 勾选",
  "PackageIcon": "包裹",
  "PackageMinusIcon": "包裹 减",
  "PackageOpenIcon": "包裹 打开",
  "PackagePlusIcon": "包裹 加",
  "PackageSearchIcon": "包裹 搜索",
  "PackageXIcon": "包裹 X",
  "PaintBucketIcon": "漆 Bucket",
  "PaintRollerIcon": "漆 滚轴",
  "Paintbrush2Icon": "画刷 2",
  "PaintbrushIcon": "画刷",
  "PaintbrushVerticalIcon": "画刷 垂直",
  "PaletteIcon": "调色板",
  "PalmtreeIcon": "棕榈树",
  "PandaIcon": "熊猫",
  "PanelBottomCloseIcon": "面板 底部 关闭",
  "PanelBottomDashedIcon": "面板 底部 虚线",
  "PanelBottomIcon": "面板 底部",
  "PanelBottomInactiveIcon": "面板 底部 未激活",
  "PanelBottomOpenIcon": "面板 底部 打开",
  "PanelLeftCloseIcon": "面板 左 关闭",
  "PanelLeftDashedIcon": "面板 左 虚线",
  "PanelLeftIcon": "面板 左",
  "PanelLeftInactiveIcon": "面板 左 未激活",
  "PanelLeftOpenIcon": "面板 左 打开",
  "PanelLeftRightDashedIcon": "面板 左 右 虚线",
  "PanelRightCloseIcon": "面板 右 关闭",
  "PanelRightDashedIcon": "面板 右 虚线",
  "PanelRightIcon": "面板 右",
  "PanelRightInactiveIcon": "面板 右 未激活",
  "PanelRightOpenIcon": "面板 右 打开",
  "PanelTopBottomDashedIcon": "面板 顶 底部 虚线",
  "PanelTopCloseIcon": "面板 顶 关闭",
  "PanelTopDashedIcon": "面板 顶 虚线",
  "PanelTopIcon": "面板 顶",
  "PanelTopInactiveIcon": "面板 顶 未激活",
  "PanelTopOpenIcon": "面板 顶 打开",
  "PanelsLeftBottomIcon": "面板 左 底部",
  "PanelsLeftRightIcon": "面板 左 右",
  "PanelsRightBottomIcon": "面板 右 底部",
  "PanelsTopBottomIcon": "面板 顶 底部",
  "PanelsTopLeftIcon": "面板 顶 左",
  "PaperclipIcon": "回形针",
  "ParenthesesIcon": "括号",
  "ParkingCircleIcon": "停车 圆",
  "ParkingCircleOffIcon": "停车 圆 关闭",
  "ParkingMeterIcon": "停车 米",
  "ParkingSquareIcon": "停车 方块",
  "ParkingSquareOffIcon": "停车 方块 关闭",
  "PartyPopperIcon": "派对 Popper",
  "PauseCircleIcon": "暂停 圆",
  "PauseIcon": "暂停",
  "PauseOctagonIcon": "暂停 八边形",
  "PawPrintIcon": "爪 Print",
  "PcCaseIcon": "机箱 大小写",
  "PenBoxIcon": "钢笔 盒子",
  "PenIcon": "钢笔",
  "PenLineIcon": "钢笔横线 编辑",
  "PenOffIcon": "钢笔 关闭",
  "PenSquareIcon": "钢笔 方块",
  "PenToolIcon": "钢笔 工具",
  "PencilIcon": "铅笔",
  "PencilLineIcon": "铅笔横线 编辑",
  "PencilOffIcon": "铅笔 关闭",
  "PencilRulerIcon": "铅笔 尺",
  "PentagonIcon": "五边形",
  "PercentCircleIcon": "百分号 圆",
  "PercentDiamondIcon": "百分号 钻石",
  "PercentIcon": "百分号",
  "PercentSquareIcon": "百分号 方块",
  "PersonStandingIcon": "人 Standing",
  "PhilippinePesoIcon": "Philippine Peso",
  "PhoneCallIcon": "电话 Call",
  "PhoneForwardedIcon": "电话 Forwarded",
  "PhoneIcon": "电话",
  "PhoneIncomingIcon": "电话 Incoming",
  "PhoneMissedIcon": "电话 Missed",
  "PhoneOffIcon": "电话 关闭",
  "PhoneOutgoingIcon": "电话 Outgoing",
  "PiIcon": "π",
  "PiSquareIcon": "π 方块",
  "PianoIcon": "钢琴",
  "PickaxeIcon": "镐",
  "PictureInPicture2Icon": "图片 进入 图片 2",
  "PictureInPictureIcon": "图片 进入 图片",
  "PieChartIcon": "饼图 图表",
  "PiggyBankIcon": "储蓄罐 Bank",
  "PilcrowIcon": "段落符",
  "PilcrowLeftIcon": "段落符 左",
  "PilcrowRightIcon": "段落符 右",
  "PilcrowSquareIcon": "段落符 方块",
  "PillBottleIcon": "药丸 瓶",
  "PillIcon": "药丸",
  "PinIcon": "大头针",
  "PinOffIcon": "大头针 关闭",
  "PipetteIcon": "移液器",
  "PizzaIcon": "披萨",
  "PlaneIcon": "飞机",
  "PlaneLandingIcon": "飞机 Landing",
  "PlaneTakeoffIcon": "飞机 Takeoff",
  "PlayCircleIcon": "播放 圆",
  "PlayIcon": "播放",
  "PlaySquareIcon": "播放 方块",
  "Plug2Icon": "插头 2",
  "PlugIcon": "插头",
  "PlugZap2Icon": "插头 闪电 2",
  "PlugZapIcon": "插头 闪电",
  "PlusCircleIcon": "加 圆",
  "PlusIcon": "加号",
  "PlusSquareIcon": "加 方块",
  "PocketIcon": "口袋",
  "PocketKnifeIcon": "口袋 刀",
  "PodcastIcon": "播客",
  "PointerIcon": "指针",
  "PointerOffIcon": "指针 关闭",
  "PopcornIcon": "爆米花",
  "PopsicleIcon": "雪糕",
  "PoundSterlingIcon": "英镑",
  "PowerCircleIcon": "电源 圆",
  "PowerIcon": "电源",
  "PowerOffIcon": "电源 关闭",
  "PowerSquareIcon": "电源 方块",
  "PresentationIcon": "演示",
  "PrinterCheckIcon": "打印机 勾选",
  "PrinterIcon": "打印机",
  "ProjectorIcon": "投影仪",
  "ProportionsIcon": "比例",
  "PuzzleIcon": "拼图",
  "PyramidIcon": "金字塔",
  "QrCodeIcon": "二维码 代码",
  "QuoteIcon": "引用",
  "RabbitIcon": "兔子",
  "RadarIcon": "雷达",
  "RadiationIcon": "辐射",
  "RadicalIcon": "根号",
  "RadioIcon": "收音机",
  "RadioReceiverIcon": "收音机 Receiver",
  "RadioTowerIcon": "收音机 塔",
  "RadiusIcon": "半径",
  "RailSymbolIcon": "铁路 符号",
  "RainbowIcon": "彩虹",
  "RatIcon": "老鼠",
  "RatioIcon": "Ratio",
  "ReceiptCentIcon": "收据 分",
  "ReceiptEuroIcon": "收据 欧元",
  "ReceiptIcon": "收据",
  "ReceiptIndianRupeeIcon": "收据 印度 卢比",
  "ReceiptJapaneseYenIcon": "收据 日本 日元",
  "ReceiptPoundSterlingIcon": "收据 英镑 英镑",
  "ReceiptRussianRubleIcon": "收据 俄罗斯 卢布",
  "ReceiptSwissFrancIcon": "收据 瑞士 法郎",
  "ReceiptTextIcon": "收据 文本",
  "ReceiptTurkishLiraIcon": "收据 土耳其 里拉",
  "RectangleCircleIcon": "矩形 圆",
  "RectangleEllipsisIcon": "矩形 省略",
  "RectangleGogglesIcon": "矩形 Goggles",
  "RectangleHorizontalIcon": "横矩形",
  "RectangleVerticalIcon": "竖矩形",
  "RecycleIcon": "回收",
  "Redo2Icon": "重做 2",
  "RedoDotIcon": "重做 点",
  "RedoIcon": "重做",
  "RefreshCcwDotIcon": "刷新",
  "RefreshCcwIcon": "逆时针刷新",
  "RefreshCwIcon": "顺时针刷新",
  "RefreshCwOffIcon": "停止刷新",
  "RefrigeratorIcon": "冰箱",
  "RegexIcon": "正则",
  "RemoveFormattingIcon": "移除 Formatting",
  "Repeat1Icon": "重复 1",
  "Repeat2Icon": "重复 2",
  "RepeatIcon": "重复",
  "ReplaceAllIcon": "替换 全部",
  "ReplaceIcon": "替换",
  "ReplyAllIcon": "回复 全部",
  "ReplyIcon": "回复",
  "RewindIcon": "倒带",
  "RibbonIcon": "丝带",
  "RocketIcon": "火箭",
  "RockingChairIcon": "摇 Chair",
  "RollerCoasterIcon": "滚轴 Coaster",
  "RoseIcon": "Rose",
  "Rotate3DIcon": "旋转 3 D",
  "Rotate3dIcon": "3D旋转",
  "RotateCcwIcon": "逆时针旋转",
  "RotateCcwKeyIcon": "旋转 逆时针 钥匙",
  "RotateCcwSquareIcon": "旋转 逆时针 方块",
  "RotateCwIcon": "顺时针旋转",
  "RotateCwSquareIcon": "旋转 顺时针 方块",
  "RouteIcon": "路线",
  "RouteOffIcon": "路线 关闭",
  "RouterIcon": "路由器",
  "Rows2Icon": "行 2",
  "Rows3Icon": "行 3",
  "Rows4Icon": "行 4",
  "RowsIcon": "行",
  "RssIcon": "RSS",
  "RulerDimensionLineIcon": "尺 Dimension 线",
  "RulerIcon": "尺",
  "RussianRubleIcon": "卢布",
  "SailboatIcon": "帆船",
  "SaladIcon": "沙拉",
  "SandwichIcon": "三明治",
  "SatelliteDishIcon": "卫星 Dish",
  "SatelliteIcon": "卫星",
  "SaudiRiyalIcon": "Saudi Riyal",
  "SaveAllIcon": "保存全部",
  "SaveIcon": "保存",
  "SaveOffIcon": "保存 关闭",
  "Scale3DIcon": "秤 3 D",
  "Scale3dIcon": "秤 3 D",
  "ScaleIcon": "秤",
  "ScalingIcon": "缩放",
  "ScanBarcodeIcon": "扫描 条码",
  "ScanEyeIcon": "扫描 眼睛",
  "ScanFaceIcon": "扫描 Face",
  "ScanHeartIcon": "扫描 心",
  "ScanIcon": "扫描",
  "ScanLineIcon": "扫描 线",
  "ScanQrCodeIcon": "扫描 二维码 代码",
  "ScanSearchIcon": "扫描 搜索",
  "ScanTextIcon": "扫描 文本",
  "ScatterChartIcon": "散布 图表",
  "School2Icon": "学校 2",
  "SchoolIcon": "学校",
  "ScissorsIcon": "剪刀",
  "ScissorsLineDashedIcon": "剪刀 线 虚线",
  "ScissorsSquareDashedBottomIcon": "剪刀 方块 虚线 底部",
  "ScissorsSquareIcon": "剪刀 方块",
  "ScreenShareIcon": "屏幕 分享",
  "ScreenShareOffIcon": "屏幕 分享 关闭",
  "ScrollIcon": "卷轴",
  "ScrollTextIcon": "卷轴 文本",
  "SearchCheckIcon": "搜索 勾选",
  "SearchCodeIcon": "搜索 代码",
  "SearchIcon": "搜索 放大镜",
  "SearchSlashIcon": "搜索 斜杠",
  "SearchXIcon": "搜索 X",
  "SectionIcon": "段",
  "SendHorizonalIcon": "发送 水平",
  "SendHorizontalIcon": "发送 水平",
  "SendIcon": "发送",
  "SendToBackIcon": "发送 到 后退",
  "SeparatorHorizontalIcon": "分隔符 水平",
  "SeparatorVerticalIcon": "分隔符 垂直",
  "ServerCogIcon": "服务器 齿轮",
  "ServerCrashIcon": "服务器 Crash",
  "ServerIcon": "服务器",
  "ServerOffIcon": "服务器 关闭",
  "Settings2Icon": "设置 齿轮",
  "SettingsIcon": "设置 齿轮",
  "ShapesIcon": "形状",
  "Share2Icon": "分享 2",
  "ShareIcon": "分享",
  "SheetIcon": "表单",
  "ShellIcon": "贝壳",
  "ShieldAlertIcon": "盾牌 警告",
  "ShieldBanIcon": "盾牌 禁止",
  "ShieldCheckIcon": "盾牌 验证",
  "ShieldCloseIcon": "盾牌 关闭",
  "ShieldEllipsisIcon": "盾牌 省略",
  "ShieldHalfIcon": "盾牌 半",
  "ShieldIcon": "盾牌",
  "ShieldMinusIcon": "盾牌 减",
  "ShieldOffIcon": "盾牌 关闭",
  "ShieldPlusIcon": "盾牌 加",
  "ShieldQuestionIcon": "盾牌 问号",
  "ShieldQuestionMarkIcon": "盾牌 问号 标记",
  "ShieldUserIcon": "盾牌 用户",
  "ShieldXIcon": "盾牌 关闭",
  "ShipIcon": "船",
  "ShipWheelIcon": "船 轮",
  "ShirtIcon": "衬衣",
  "ShoppingBagIcon": "购物 Bag",
  "ShoppingBasketIcon": "购物 Basket",
  "ShoppingCartIcon": "购物 Cart",
  "ShovelIcon": "铲",
  "ShowerHeadIcon": "淋浴 Head",
  "ShredderIcon": "Shredder",
  "ShrimpIcon": "Shrimp",
  "ShrinkIcon": "收缩",
  "ShrubIcon": "灌木",
  "ShuffleIcon": "随机",
  "SidebarCloseIcon": "侧边栏 关闭",
  "SidebarIcon": "侧边栏",
  "SidebarOpenIcon": "侧边栏 打开",
  "SigmaIcon": "Σ",
  "SigmaSquareIcon": "Σ 方块",
  "SignalHighIcon": "信号 高",
  "SignalIcon": "信号",
  "SignalLowIcon": "信号 低",
  "SignalMediumIcon": "信号 中",
  "SignalZeroIcon": "信号 零",
  "SignatureIcon": "签名",
  "SignpostBigIcon": "路牌 大",
  "SignpostIcon": "路牌",
  "SirenIcon": "警报",
  "SkipBackIcon": "跳过 后退",
  "SkipForwardIcon": "跳过 前进",
  "SkullIcon": "骷髅",
  "SlackIcon": "Slack",
  "SlashIcon": "斜杠",
  "SlashSquareIcon": "斜杠 方块",
  "SliceIcon": "切片",
  "SlidersHorizontalIcon": "滑块 水平",
  "SlidersIcon": "滑块",
  "SlidersVerticalIcon": "滑块 垂直",
  "SmartphoneChargingIcon": "智能手机 Charging",
  "SmartphoneIcon": "智能手机",
  "SmartphoneNfcIcon": "智能手机 NFC",
  "SmileIcon": "笑脸",
  "SmilePlusIcon": "笑脸 加",
  "SnailIcon": "蜗牛",
  "SnowflakeIcon": "雪花",
  "SoapDispenserDropletIcon": "Soap Dispenser 水滴",
  "SofaIcon": "沙发",
  "SolarPanelIcon": "太阳能 面板",
  "SortAscIcon": "排序 Asc",
  "SortDescIcon": "排序 Desc",
  "SoupIcon": "汤",
  "SpaceIcon": "空格",
  "SpadeIcon": "黑桃",
  "SparkleIcon": "闪光",
  "SparklesIcon": "闪光",
  "SpeakerIcon": "扬声器",
  "SpeechIcon": "言语",
  "SpellCheck2Icon": "拼写 勾选 2",
  "SpellCheckIcon": "拼写 勾选",
  "SplineIcon": "曲线",
  "SplinePointerIcon": "曲线 指针",
  "SplitIcon": "分割",
  "SplitSquareHorizontalIcon": "分割 方块 水平",
  "SplitSquareVerticalIcon": "分割 方块 垂直",
  "SpoolIcon": "Spool",
  "SpotlightIcon": "Spotlight",
  "SprayCanIcon": "喷雾 Can",
  "SproutIcon": "嫩芽",
  "SquareActivityIcon": "方块 活动 心电图",
  "SquareArrowDownIcon": "方块 箭头 下",
  "SquareArrowDownLeftIcon": "方块 箭头 下 左",
  "SquareArrowDownRightIcon": "方块 箭头 下 右",
  "SquareArrowLeftIcon": "方块 箭头 左",
  "SquareArrowOutDownLeftIcon": "方块 箭头 出 下 左",
  "SquareArrowOutDownRightIcon": "方块 箭头 出 下 右",
  "SquareArrowOutUpLeftIcon": "方块 箭头 出 上 左",
  "SquareArrowOutUpRightIcon": "方块 箭头 出 上 右",
  "SquareArrowRightIcon": "方块 箭头 右",
  "SquareArrowUpIcon": "方块 箭头 上",
  "SquareArrowUpLeftIcon": "方块 箭头 上 左",
  "SquareArrowUpRightIcon": "方块 箭头 上 右",
  "SquareAsteriskIcon": "方块 星号",
  "SquareBottomDashedScissorsIcon": "方块 底部 虚线 剪刀",
  "SquareChartGanttIcon": "方块 图表 甘特图",
  "SquareCheckBigIcon": "大勾选 方",
  "SquareCheckIcon": "勾选 方",
  "SquareChevronDownIcon": "方块 箭头 下",
  "SquareChevronLeftIcon": "方块 箭头 左",
  "SquareChevronRightIcon": "方块 箭头 右",
  "SquareChevronUpIcon": "方块 箭头 上",
  "SquareCodeIcon": "方块 代码",
  "SquareDashedBottomCodeIcon": "方块 虚线 底部 代码",
  "SquareDashedBottomIcon": "方块 虚线 底部",
  "SquareDashedIcon": "方块 虚线",
  "SquareDashedKanbanIcon": "方块 虚线 看板",
  "SquareDashedMousePointerIcon": "方块 虚线 鼠标 指针",
  "SquareDashedTopSolidIcon": "方块 虚线 顶 Solid",
  "SquareDivideIcon": "方块 除",
  "SquareDotIcon": "方块 点",
  "SquareEqualIcon": "方块 等号",
  "SquareFunctionIcon": "方块 函数",
  "SquareGanttChartIcon": "方块 甘特图 图表",
  "SquareIcon": "方块",
  "SquareKanbanIcon": "方块 看板",
  "SquareLibraryIcon": "方块 图书馆",
  "SquareMIcon": "方块 M",
  "SquareMenuIcon": "方块 菜单",
  "SquareMinusIcon": "减号 方",
  "SquareMousePointerIcon": "方块 鼠标 指针",
  "SquareParkingIcon": "方块 停车",
  "SquareParkingOffIcon": "方块 停车 关闭",
  "SquarePauseIcon": "方块 暂停",
  "SquarePenIcon": "编辑 方",
  "SquarePercentIcon": "方块 百分号",
  "SquarePiIcon": "方块 π",
  "SquarePilcrowIcon": "方块 段落符",
  "SquarePlayIcon": "方块 播放",
  "SquarePlusIcon": "加号 方",
  "SquarePowerIcon": "方块 电源",
  "SquareRadicalIcon": "方块 根号",
  "SquareRoundCornerIcon": "方块 圆 转角",
  "SquareScissorsIcon": "方块 剪刀",
  "SquareSigmaIcon": "方块 Σ",
  "SquareSlashIcon": "禁止 方",
  "SquareSplitHorizontalIcon": "方块 分割 水平",
  "SquareSplitVerticalIcon": "方块 分割 垂直",
  "SquareSquareIcon": "方块 方块",
  "SquareStackIcon": "方块 栈",
  "SquareStarIcon": "方块 星",
  "SquareStopIcon": "方块 停止",
  "SquareTerminalIcon": "方块 终端",
  "SquareUserIcon": "用户 方",
  "SquareUserRoundIcon": "用户头像 方",
  "SquareXIcon": "关闭 方",
  "SquaresExcludeIcon": "方块 Exclude",
  "SquaresIntersectIcon": "方块 Intersect",
  "SquaresSubtractIcon": "方块 Subtract",
  "SquaresUniteIcon": "方块 Unite",
  "SquircleDashedIcon": "圆角方块 虚线",
  "SquircleIcon": "圆角方块",
  "SquirrelIcon": "松鼠",
  "StampIcon": "印章",
  "StarHalfIcon": "星 半",
  "StarIcon": "星",
  "StarOffIcon": "星 关闭",
  "StarsIcon": "星群",
  "StepBackIcon": "步 后退",
  "StepForwardIcon": "步 前进",
  "StethoscopeIcon": "听诊器",
  "StickerIcon": "贴纸",
  "StickyNoteIcon": "便利 Note",
  "StopCircleIcon": "停止 圆",
  "StoreIcon": "商店",
  "StretchHorizontalIcon": "拉伸 水平",
  "StretchVerticalIcon": "拉伸 垂直",
  "StrikethroughIcon": "删除线",
  "SubscriptIcon": "下标",
  "SubtitlesIcon": "字幕",
  "SunDimIcon": "太阳 暗",
  "SunIcon": "太阳 亮色模式",
  "SunMediumIcon": "太阳 中",
  "SunMoonIcon": "日月 切换主题",
  "SunSnowIcon": "太阳雪",
  "SunriseIcon": "日出",
  "SunsetIcon": "日落",
  "SuperscriptIcon": "上标",
  "SwatchBookIcon": "色板 书",
  "SwissFrancIcon": "瑞士 法郎",
  "SwitchCameraIcon": "Switch 相机",
  "SwordIcon": "剑",
  "SwordsIcon": "剑",
  "SyringeIcon": "注射器",
  "Table2Icon": "表格 2",
  "TableCellsMergeIcon": "表格 单元格 合并",
  "TableCellsSplitIcon": "表格 单元格 分割",
  "TableColumnsSplitIcon": "表格 列 分割",
  "TableConfigIcon": "表格 Config",
  "TableIcon": "表格",
  "TableOfContentsIcon": "表格 Of Contents",
  "TablePropertiesIcon": "表格 Properties",
  "TableRowsSplitIcon": "表格 行 分割",
  "TabletIcon": "平板",
  "TabletSmartphoneIcon": "平板 智能手机",
  "TabletsIcon": "药片",
  "TagIcon": "标签",
  "TagsIcon": "标签",
  "Tally1Icon": "计数 1",
  "Tally2Icon": "计数 2",
  "Tally3Icon": "计数 3",
  "Tally4Icon": "计数 4",
  "Tally5Icon": "计数 5",
  "TangentIcon": "切线",
  "TargetIcon": "靶心",
  "TelescopeIcon": "望远镜",
  "TentIcon": "帐篷",
  "TentTreeIcon": "帐篷 树",
  "TerminalIcon": "终端 控制台",
  "TerminalSquareIcon": "终端 方块",
  "TestTube2Icon": "测试 管 2",
  "TestTubeDiagonalIcon": "测试 管 Diagonal",
  "TestTubeIcon": "测试 管",
  "TestTubesIcon": "测试 管",
  "TextAlignCenterIcon": "文本 对齐 居中",
  "TextAlignEndIcon": "文本 对齐 末",
  "TextAlignJustifyIcon": "文本 对齐 两端对齐",
  "TextAlignStartIcon": "文本 对齐 开始",
  "TextCursorIcon": "文本 光标",
  "TextCursorInputIcon": "文本 光标 输入",
  "TextIcon": "文本",
  "TextInitialIcon": "文本 Initial",
  "TextQuoteIcon": "文本 引用",
  "TextSearchIcon": "文本 搜索",
  "TextSelectIcon": "文本 选择",
  "TextSelectionIcon": "文本 Selection",
  "TextWrapIcon": "文本 换行",
  "TheaterIcon": "剧院",
  "ThermometerIcon": "温度计",
  "ThermometerSnowflakeIcon": "温度计 雪花",
  "ThermometerSunIcon": "温度计 太阳",
  "ThumbsDownIcon": "点赞 下",
  "ThumbsUpIcon": "点赞 上",
  "TicketCheckIcon": "票 勾选",
  "TicketIcon": "票",
  "TicketMinusIcon": "票 减",
  "TicketPercentIcon": "票 百分号",
  "TicketPlusIcon": "票 加",
  "TicketSlashIcon": "票 斜杠",
  "TicketXIcon": "票 X",
  "TicketsIcon": "票",
  "TicketsPlaneIcon": "票 飞机",
  "TimerIcon": "计时器",
  "TimerOffIcon": "计时器 关闭",
  "TimerResetIcon": "计时器 重置",
  "ToggleLeftIcon": "开关 左",
  "ToggleRightIcon": "开关 右",
  "ToiletIcon": "马桶",
  "ToolCaseIcon": "工具 大小写",
  "TornadoIcon": "龙卷风",
  "TorusIcon": "圆环",
  "TouchpadIcon": "触摸板",
  "TouchpadOffIcon": "触摸板 关闭",
  "TowerControlIcon": "塔 Control",
  "ToyBrickIcon": "玩具 砖",
  "TractorIcon": "拖拉机",
  "TrafficConeIcon": "交通 圆锥",
  "TrainFrontIcon": "火车 前",
  "TrainFrontTunnelIcon": "火车 前 隧道",
  "TrainIcon": "火车",
  "TrainTrackIcon": "火车 Track",
  "TramFrontIcon": "电车 前",
  "TransgenderIcon": "Transgender",
  "Trash2Icon": "删除 垃圾桶",
  "TrashIcon": "删除 垃圾桶",
  "TreeDeciduousIcon": "树 Deciduous",
  "TreePalmIcon": "树 Palm",
  "TreePineIcon": "树 Pine",
  "TreesIcon": "树林",
  "TrelloIcon": "Trello",
  "TrendingDownIcon": "趋势 下",
  "TrendingUpDownIcon": "趋势 上 下",
  "TrendingUpIcon": "趋势 上",
  "TriangleAlertIcon": "警告 三角",
  "TriangleDashedIcon": "三角形 虚线",
  "TriangleIcon": "三角形",
  "TriangleRightIcon": "三角形 右",
  "TrophyIcon": "奖杯",
  "TruckElectricIcon": "卡车 电",
  "TruckIcon": "卡车",
  "TurkishLiraIcon": "土耳其 里拉",
  "TurntableIcon": "Turntable",
  "TurtleIcon": "乌龟",
  "Tv2Icon": "电视 2",
  "TvIcon": "电视",
  "TvMinimalIcon": "电视 极简",
  "TvMinimalPlayIcon": "电视 极简 播放",
  "TwitchIcon": "Twitch",
  "TwitterIcon": "推特",
  "TypeIcon": "文字",
  "TypeOutlineIcon": "文字 Outline",
  "UmbrellaIcon": "雨伞",
  "UmbrellaOffIcon": "雨伞 关闭",
  "UnderlineIcon": "下划线",
  "Undo2Icon": "撤销 2",
  "UndoDotIcon": "撤销 点",
  "UndoIcon": "撤销",
  "UnfoldHorizontalIcon": "展开 水平",
  "UnfoldVerticalIcon": "展开 垂直",
  "UngroupIcon": "Ungroup",
  "UniversityIcon": "University",
  "Unlink2Icon": "取消链接 2",
  "UnlinkIcon": "取消链接",
  "UnlockIcon": "解锁",
  "UnlockKeyholeIcon": "解锁",
  "UnplugIcon": "拔插头",
  "UploadCloudIcon": "上传 云",
  "UploadIcon": "上传",
  "UsbIcon": "USB",
  "User2Icon": "用户 2",
  "UserCheck2Icon": "用户 勾选 2",
  "UserCheckIcon": "用户 勾选",
  "UserCircle2Icon": "用户 圆 2",
  "UserCircleIcon": "用户 圆",
  "UserCog2Icon": "用户 齿轮 2",
  "UserCogIcon": "用户 齿轮",
  "UserIcon": "用户",
  "UserLockIcon": "用户 锁定",
  "UserMinus2Icon": "用户 减 2",
  "UserMinusIcon": "用户 减",
  "UserPenIcon": "用户 钢笔",
  "UserPlus2Icon": "用户 加 2",
  "UserPlusIcon": "用户 加",
  "UserRoundCheckIcon": "用户 圆 勾选",
  "UserRoundCogIcon": "用户 圆 齿轮",
  "UserRoundIcon": "用户 圆",
  "UserRoundMinusIcon": "用户 圆 减",
  "UserRoundPenIcon": "用户 圆 钢笔",
  "UserRoundPlusIcon": "用户 圆 加",
  "UserRoundSearchIcon": "用户 圆 搜索",
  "UserRoundXIcon": "用户 圆 X",
  "UserSearchIcon": "用户 搜索",
  "UserSquare2Icon": "用户 方块 2",
  "UserSquareIcon": "用户 方块",
  "UserStarIcon": "用户 星",
  "UserX2Icon": "用户 X 2",
  "UserXIcon": "用户 X",
  "Users2Icon": "用户群 2",
  "UsersIcon": "用户群",
  "UsersRoundIcon": "用户群 圆",
  "UtensilsCrossedIcon": "餐具 交叉",
  "UtensilsIcon": "餐具",
  "UtilityPoleIcon": "电线 Pole",
  "VariableIcon": "变量",
  "VaultIcon": "保险柜",
  "VectorSquareIcon": "向量 方块",
  "VeganIcon": "素食",
  "VenetianMaskIcon": "威尼斯 面具",
  "VenusAndMarsIcon": "金星 And 火星",
  "VenusIcon": "金星",
  "VerifiedIcon": "已验证",
  "VibrateIcon": "震动",
  "VibrateOffIcon": "震动 关闭",
  "VideoIcon": "视频",
  "VideoOffIcon": "视频 关闭",
  "VideotapeIcon": "Videotape",
  "ViewIcon": "查看",
  "VoicemailIcon": "语音邮件",
  "VolleyballIcon": "排球",
  "Volume1Icon": "音量 小",
  "Volume2Icon": "音量 大",
  "VolumeIcon": "音量",
  "VolumeOffIcon": "静音",
  "VolumeXIcon": "静音",
  "VoteIcon": "投票",
  "Wallet2Icon": "钱包 2",
  "WalletCardsIcon": "钱包 Cards",
  "WalletIcon": "钱包",
  "WalletMinimalIcon": "钱包 极简",
  "WallpaperIcon": "壁纸",
  "Wand2Icon": "魔棒 2",
  "WandIcon": "魔棒",
  "WandSparklesIcon": "魔棒 闪光",
  "WarehouseIcon": "仓库",
  "WashingMachineIcon": "洗衣 Machine",
  "WatchIcon": "手表",
  "WavesArrowDownIcon": "波浪 箭头 下",
  "WavesArrowUpIcon": "波浪 箭头 上",
  "WavesIcon": "波浪",
  "WavesLadderIcon": "波浪 Ladder",
  "WaypointsIcon": "路径点",
  "WebcamIcon": "摄像头",
  "WebhookIcon": "Webhook",
  "WebhookOffIcon": "Webhook 关闭",
  "WeightIcon": "重量",
  "WheatIcon": "麦穗",
  "WheatOffIcon": "麦穗 关闭",
  "WholeWordIcon": "完整 单词",
  "WifiCogIcon": "WiFi 齿轮",
  "WifiHighIcon": "WiFi 强",
  "WifiIcon": "WiFi",
  "WifiLowIcon": "WiFi 弱",
  "WifiOffIcon": "WiFi 关闭",
  "WifiPenIcon": "WiFi 钢笔",
  "WifiSyncIcon": "WiFi 同步",
  "WifiZeroIcon": "WiFi 零",
  "WindArrowDownIcon": "风 箭头 下",
  "WindIcon": "风",
  "WineIcon": "红酒",
  "WineOffIcon": "红酒 关闭",
  "WorkflowIcon": "工作流",
  "WormIcon": "Worm",
  "WrapTextIcon": "换行 文本",
  "WrenchIcon": "扳手",
  "XCircleIcon": "X 圆",
  "XIcon": "X 关闭",
  "XOctagonIcon": "X 八边形",
  "XSquareIcon": "X 方块",
  "YoutubeIcon": "YouTube",
  "ZapIcon": "闪电 速度",
  "ZapOffIcon": "闪电 关闭",
  "ZoomInIcon": "缩放 进入",
  "ZoomOutIcon": "缩放 出"
};
